//! Database independent core of Mabat.
//!
//! - [`shape`]: the static description of a view, generated by `#[derive(View)]`
//! - [`plan`]: the tree of queries that fills a view
//! - [`selection`]: the fields of a view to load
//! - [`filter`]: conditions on the rows of the root query
//! - [`sql`]: rendering a query plan as PostgreSQL

pub mod filter;
pub mod plan;
pub mod selection;
pub mod shape;
pub mod sql;

pub use plan::{ChildPlan, ChildQuery, Cte, Link, PlanError, QueryPlan, SelectColumn};
pub use plan::{SumPlan, VariantPlan};
pub use selection::{Selection, SelectionError};
pub use shape::{
    Child, EmbeddedKind, EmbeddedShape, Field, FieldKind, OrderBy, Recursion, Scalar, SumShape, SumStrategy, Through,
    ValueType, Variant, VariantData, ViewShape,
};

/// Alias of the key column of the entity selected by a query.
pub const KEY_ALIAS: &str = "$key";

/// Alias of the foreign key column that links a child row to its parent.
pub const PARENT_ALIAS: &str = "$parent";

/// Name of the root query of a plan, see [`QueryPlan::query_name`].
pub const ROOT_QUERY: &str = "$root";

/// Last segment of the alias of the tag column of an enum, e.g. `status.$tag`.
pub const TAG_ALIAS: &str = "$tag";

/// Alias of the column that places an element in an ordered list.
pub const INDEX_ALIAS: &str = "$index";

/// Alias of the column whose value is the key of an element in a map.
pub const MAP_KEY_ALIAS: &str = "$map_key";

/// Prefix of the alias of a to-one foreign key column, followed by the field name.
pub const REF_ALIAS_PREFIX: &str = "$ref.";
