//! Static description of views.
//!
//! A shape is generated by `#[derive(View)]` as a `static` and is never modified.
//! Shapes reference each other through function pointers so that views can refer to
//! other views, including themselves.

/// The shape of a view: an entity loaded from one table, with its fields.
#[derive(Debug)]
pub struct ViewShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    /// Table the entity is loaded from.
    pub table: &'static str,
    /// Primary key column, used to attach children and resolve references.
    pub key_column: &'static str,
    pub fields: &'static [Field],
}

/// The shape of a value stored in the row of the enclosing view: a struct whose fields are
/// columns of the view's table, or an enum.
#[derive(Debug)]
pub struct EmbeddedShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    pub kind: EmbeddedKind,
}

#[derive(Debug)]
pub enum EmbeddedKind {
    /// A struct. Only [`FieldKind::Column`] and [`FieldKind::Embedded`] fields.
    Product { fields: &'static [Field] },
    /// An enum.
    Sum(SumShape),
}

/// The shape of an enum: a tag column that names the variant, and the data of each variant.
#[derive(Debug)]
pub struct SumShape {
    /// Column holding the tag value of the variant, selected as text.
    pub tag_column: &'static str,
    pub strategy: SumStrategy,
    /// Ignore non-null columns of other variants than the tag names, instead of failing.
    pub lenient: bool,
    pub variants: &'static [Variant],
}

/// Where the data of the variants of an enum is stored.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SumStrategy {
    /// In columns of the enclosing view's table, next to the tag column.
    Tag,
    /// In a table per variant, whose key is the key of the enclosing view.
    TablePerVariant,
}

#[derive(Debug)]
pub struct Variant {
    /// Name of the Rust variant, which is also its path segment.
    pub name: &'static str,
    /// Value of the tag column for the variant.
    pub tag_value: &'static str,
    pub data: VariantData,
}

#[derive(Debug)]
pub enum VariantData {
    /// No data.
    Unit,
    /// Columns of the enclosing view's table ([`SumStrategy::Tag`]). Tuple fields are named
    /// `0`, `1`, ...
    Columns { fields: &'static [Field] },
    /// A row of the variant's table, keyed by the key of the enclosing view
    /// ([`SumStrategy::TablePerVariant`]).
    Table { shape: fn() -> &'static ViewShape },
}

#[derive(Debug)]
pub struct Field {
    /// Name of the Rust field, which is also its path segment.
    pub name: &'static str,
    pub kind: FieldKind,
}

#[derive(Debug)]
pub enum FieldKind {
    /// A column of the view's table, holding values of the Rust type `ty`.
    Column { column: &'static str, ty: ValueType },
    /// A struct or an enum stored in the view's row, optionally with a common column prefix.
    Embedded { column_prefix: &'static str, shape: fn() -> &'static EmbeddedShape },
    /// A to-many collection loaded by a child query: rows of the child table whose `fk`
    /// column references the key of this view, or with [`Child::through`], rows linked to
    /// this view by a link table.
    Child(Child),
    /// A to-one reference: the `fk` column of this view references the key of the target view.
    /// With `graph`, the value is a reference into a graph (`Ref<T>`), not an owned value. With
    /// `recursion`, the reference leads back to its own view, as a chain of parents does.
    ToOne {
        fk: &'static str,
        optional: bool,
        shape: fn() -> &'static ViewShape,
        graph: bool,
        recursion: Option<Recursion>,
    },
}

impl FieldKind {
    /// `true` for a relationship to entities of a graph, see [`Child::graph`].
    pub fn is_graph_edge(&self) -> bool {
        match self {
            FieldKind::Child(child) => child.graph,
            FieldKind::ToOne { graph, .. } => *graph,
            _ => false,
        }
    }
}

/// The Rust type of a column field, as a schema such as GraphQL's describes it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ValueType {
    pub scalar: Scalar,
    /// An `Option`.
    pub nullable: bool,
    /// A list of values, such as `Vec<String>` for a PostgreSQL array.
    pub list: bool,
}

impl ValueType {
    /// A `String`.
    pub const TEXT: ValueType = ValueType::new(Scalar::String);

    pub const fn new(scalar: Scalar) -> ValueType {
        ValueType { scalar, nullable: false, list: false }
    }

    /// The value type of the Rust type `T`, from its name, as `#[derive(View)]` finds it from
    /// the type as written: for a field whose type is a type parameter of a generic embedded
    /// struct, known only when the struct is instantiated.
    pub fn of<T: ?Sized>() -> ValueType {
        ValueType::of_type_name(std::any::type_name::<T>())
    }

    /// The value type of a Rust type by its full name, as `std::any::type_name` writes it.
    pub fn of_type_name(name: &'static str) -> ValueType {
        let generic = |name: &'static str, outer: &str| -> Option<&'static str> {
            let start = name.find('<')?;
            let path = &name[..start];
            (path.rsplit("::").next() == Some(outer)).then(|| &name[start + 1..name.len() - 1])
        };
        let last = |name: &'static str| -> &'static str {
            let path = name.split('<').next().unwrap_or(name);
            path.rsplit("::").next().unwrap_or(path)
        };
        let (nullable, name) = match generic(name, "Option") {
            Some(inner) => (true, inner),
            None => (false, name),
        };
        let (list, name) = match generic(name, "Vec") {
            Some(inner) if last(inner) != "u8" => (true, inner),
            _ => (false, name),
        };
        let scalar = match last(name) {
            "Vec" => Scalar::Bytes,
            "bool" => Scalar::Boolean,
            "i8" | "i16" | "i32" | "u8" | "u16" => Scalar::Int,
            "i64" | "u32" | "u64" | "i128" | "u128" | "isize" | "usize" => Scalar::BigInt,
            "f32" | "f64" => Scalar::Float,
            "String" | "str" | "char" => Scalar::String,
            "Uuid" => Scalar::Uuid,
            "NaiveDate" => Scalar::Date,
            "NaiveTime" => Scalar::Time,
            "DateTime" => Scalar::DateTime,
            "NaiveDateTime" => Scalar::NaiveDateTime,
            "Decimal" | "BigDecimal" => Scalar::Decimal,
            "Value" => Scalar::Json,
            other => Scalar::Other(other),
        };
        ValueType { scalar, nullable, list }
    }
}

/// The kind of value of a column, from the name of its Rust type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scalar {
    /// `bool`
    Boolean,
    /// Integers that fit 32 bits: `i8`, `i16`, `i32`, `u8`, `u16`
    Int,
    /// Larger integers: `i64`, `u32`, `u64`, `i128`, `u128`, `isize`, `usize`
    BigInt,
    /// `f32`, `f64`
    Float,
    /// `String`, `str`, `char`
    String,
    /// `Uuid`
    Uuid,
    /// `NaiveDate`
    Date,
    /// `NaiveTime`
    Time,
    /// `DateTime<Utc>` and other time zones: a point in time
    DateTime,
    /// `NaiveDateTime`: a date and time without a time zone
    NaiveDateTime,
    /// `Decimal`, `BigDecimal`
    Decimal,
    /// A `#[view(json)]` field, or `serde_json::Value`
    Json,
    /// `Vec<u8>`
    Bytes,
    /// Any other type, by the name of its last path segment, such as an enum with
    /// `sqlx::Type`.
    Other(&'static str),
}

/// A to-many collection, see [`FieldKind::Child`].
#[derive(Debug)]
pub struct Child {
    /// The column referencing the key of the containing view: of the child table, or of the
    /// link table with `through`.
    pub fk: &'static str,
    pub order_by: &'static [OrderBy],
    pub shape: fn() -> &'static ViewShape,
    /// A many-to-many collection through a link table.
    pub through: Option<Through>,
    /// A column whose integer value places each element in the list, whatever the order of
    /// the rows. Of the link table with `through`.
    pub index: Option<&'static str>,
    /// A column whose value is the key of each element in a map. Of the link table with
    /// `through`.
    pub map_key: Option<&'static str>,
    /// The collection contains the view it is a field of, directly or indirectly.
    pub recursion: Option<Recursion>,
    /// The elements are references into a graph (`Vec<Ref<T>>`), not owned values.
    pub graph: bool,
}

impl Child {
    /// A collection whose `fk` column references the key of the containing view.
    pub const fn new(fk: &'static str, shape: fn() -> &'static ViewShape) -> Child {
        Child { fk, order_by: &[], shape, through: None, index: None, map_key: None, recursion: None, graph: false }
    }
}

/// The link table of a many-to-many collection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Through {
    pub table: &'static str,
    /// The column of the link table referencing the key of the child view.
    pub target: &'static str,
}

/// How a recursive collection or to-one reference is loaded.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Recursion {
    /// One query per level, at most `depth` levels.
    Depth(u32),
    /// One `WITH RECURSIVE` query for all levels, at most `depth` levels if given. Only for a
    /// field that leads to its own view directly.
    Cte { depth: Option<u32> },
}

/// A column to order by.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OrderBy {
    pub column: &'static str,
    pub descending: bool,
}

impl OrderBy {
    pub const fn asc(column: &'static str) -> Self {
        OrderBy { column, descending: false }
    }

    pub const fn desc(column: &'static str) -> Self {
        OrderBy { column, descending: true }
    }
}
