//! The Rust types of the columns of a view, used to check queries against the view.

use sqlx::{Type, TypeInfo};

use crate::ViewDecoder;
use crate::backend::Backend;

/// The `describe` function of a view, for a database.
pub type DescribeFn<B> = fn(&mut Description<B>);

/// The columns of a view with their Rust types, and the views of its child queries.
///
/// Filled by the `describe` function generated by `#[derive(View)]`.
pub struct Description<B: Backend> {
    pub(crate) columns: Vec<ColumnType>,
    /// Describe functions of the views of child and to-one fields, by field index, with the
    /// type of the map key of a map collection.
    pub(crate) children: Vec<(usize, DescribeFn<B>, Option<ColumnType>)>,
    /// Describe functions of the variants of enums stored in a table per variant, by field
    /// index and variant.
    pub(crate) variants: Vec<(usize, &'static str, DescribeFn<B>)>,
}

impl<B: Backend> Default for Description<B> {
    fn default() -> Self {
        Description { columns: Vec::new(), children: Vec::new(), variants: Vec::new() }
    }
}

/// A column of a view and the Rust type it is decoded as.
pub(crate) struct ColumnType {
    pub(crate) alias: String,
    /// `true` for an `Option` field, which may be left out of an override.
    pub(crate) optional: bool,
    pub(crate) rust_type: &'static str,
    /// The database type the Rust type is usually stored as, for messages.
    pub(crate) sql_type: String,
    /// The names of the database types the Rust type can be decoded from.
    pub(crate) accepts: Vec<String>,
}

/// The names of the types of database `B` that `T` can be decoded from, as the driver names
/// them: the built-in types `T` is compatible with, and types the driver knows only by name.
fn accepted_types<T: Type<B>, B: Backend>() -> Vec<String> {
    let mut names: Vec<String> = B::type_catalog().iter().filter(|ty| T::compatible(ty)).map(B::type_name).collect();
    for name in B::named_types::<T>() {
        if !names.iter().any(|n| n.eq_ignore_ascii_case(&name)) {
            names.push(name);
        }
    }
    names
}

impl<B: Backend> Description<B> {
    /// A column decoded as `T`, with the given alias.
    pub fn column<T: Type<B>>(&mut self, alias: impl Into<String>, optional: bool) {
        self.columns.push(ColumnType {
            alias: alias.into(),
            optional,
            rust_type: std::any::type_name::<T>(),
            sql_type: T::type_info().name().to_string(),
            accepts: accepted_types::<T, B>(),
        });
    }

    /// A child or to-one field whose values are views of type `C`.
    pub fn view<C: ViewDecoder<B>>(&mut self, field_index: usize) {
        self.children.push((field_index, C::describe, None));
    }

    /// A map collection whose values are views of type `C`, keyed by `K`.
    pub fn map<K: Type<B>, C: ViewDecoder<B>>(&mut self, field_index: usize) {
        let mut key = Description::<B>::default();
        key.column::<K>(mabat_core::MAP_KEY_ALIAS, false);
        self.children.push((field_index, C::describe, key.columns.pop()));
    }

    /// The variant `variant` of an enum stored in a table per variant in the field
    /// `field_index`, whose columns are described by `describe`.
    pub fn variant_table(&mut self, field_index: usize, variant: &'static str, describe: DescribeFn<B>) {
        self.variants.push((field_index, variant, describe));
    }

    pub(crate) fn variant(&self, field_index: usize, variant: &str) -> Option<DescribeFn<B>> {
        self.variants.iter().find(|(i, v, _)| *i == field_index && *v == variant).map(|(_, _, describe)| *describe)
    }

    pub(crate) fn column_type(&self, alias: &str) -> Option<&ColumnType> {
        self.columns.iter().find(|c| c.alias == alias)
    }

    /// The describe function of a child field, and the type of its map key.
    pub(crate) fn child(&self, field_index: usize) -> Option<(DescribeFn<B>, Option<&ColumnType>)> {
        self.children.iter().find(|(i, _, _)| *i == field_index).map(|(_, describe, key)| (*describe, key.as_ref()))
    }
}

/// A type name without module paths: `Option<String>` for
/// `core::option::Option<alloc::string::String>`.
pub(crate) fn short_type_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut segment = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' || c == ':' {
            segment.push(c);
        } else {
            out.push_str(segment.rsplit("::").next().unwrap_or(""));
            segment.clear();
            out.push(c);
        }
    }
    out.push_str(segment.rsplit("::").next().unwrap_or(""));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "postgres")]
    #[test]
    fn accepted_postgres_types() {
        use sqlx::Postgres;
        assert_eq!(accepted_types::<String, Postgres>(), ["NAME", "TEXT", "UNKNOWN", "CHAR", "VARCHAR", "citext"]);
        assert_eq!(accepted_types::<Vec<String>, Postgres>(), ["NAME[]", "TEXT[]", "CHAR[]", "VARCHAR[]"]);
        assert_eq!(accepted_types::<i64, Postgres>(), ["INT8"]);
        assert_eq!(accepted_types::<Option<i32>, Postgres>(), ["INT4"]);
        assert_eq!(accepted_types::<bool, Postgres>(), ["BOOL"]);
        assert_eq!(accepted_types::<uuid::Uuid, Postgres>(), ["UUID"]);
        assert_eq!(accepted_types::<sqlx::types::Json<serde_json::Value>, Postgres>(), ["JSON", "JSONB"]);
        assert_eq!(accepted_types::<Vec<i64>, Postgres>(), ["INT8[]"]);
    }

    #[test]
    fn short_type_names() {
        assert_eq!(short_type_name("core::option::Option<alloc::string::String>"), "Option<String>");
        assert_eq!(short_type_name("i64"), "i64");
        assert_eq!(short_type_name("chrono::DateTime<chrono::offset::utc::Utc>"), "DateTime<Utc>");
    }
}
