//! The Rust types of the columns of a view, used to check queries against the view.

use sqlx::postgres::{PgTypeInfo, PgTypeKind};
use sqlx::{Postgres, Type, TypeInfo};

use crate::View;

/// The `describe` function of a view.
pub type DescribeFn = fn(&mut Description);

/// The columns of a view with their Rust types, and the views of its child queries.
///
/// Filled by the `describe` function generated by `#[derive(View)]`.
#[derive(Default)]
pub struct Description {
    pub(crate) columns: Vec<ColumnType>,
    /// Describe functions of the views of child and to-one fields, by field index, with the
    /// type of the map key of a map collection.
    pub(crate) children: Vec<(usize, DescribeFn, Option<ColumnType>)>,
    /// Describe functions of the variants of enums stored in a table per variant, by field
    /// index and variant.
    pub(crate) variants: Vec<(usize, &'static str, DescribeFn)>,
}

/// A column of a view and the Rust type it is decoded as.
pub(crate) struct ColumnType {
    pub(crate) alias: String,
    /// `true` for an `Option` field, which may be left out of an override.
    pub(crate) optional: bool,
    pub(crate) rust_type: &'static str,
    /// The PostgreSQL type the Rust type is usually stored as, for messages.
    pub(crate) sql_type: String,
    /// The names of the PostgreSQL types the Rust type can be decoded from.
    pub(crate) accepts: Vec<String>,
}

/// The names of the built-in PostgreSQL types as SQLx names them, and common extension
/// types. Each has an array type, named with `[]`.
const TYPE_NAMES: &[&str] = &[
    "BOOL",
    "BYTEA",
    "CHAR",
    "NAME",
    "INT8",
    "INT2",
    "INT4",
    "TEXT",
    "OID",
    "JSON",
    "POINT",
    "LSEG",
    "PATH",
    "BOX",
    "POLYGON",
    "LINE",
    "CIDR",
    "FLOAT4",
    "FLOAT8",
    "UNKNOWN",
    "CIRCLE",
    "MACADDR8",
    "MACADDR",
    "INET",
    "BPCHAR",
    "VARCHAR",
    "DATE",
    "TIME",
    "TIMESTAMP",
    "TIMESTAMPTZ",
    "INTERVAL",
    "TIMETZ",
    "BIT",
    "VARBIT",
    "NUMERIC",
    "RECORD",
    "UUID",
    "JSONB",
    "INT4RANGE",
    "NUMRANGE",
    "TSRANGE",
    "TSTZRANGE",
    "DATERANGE",
    "INT8RANGE",
    "JSONPATH",
    "MONEY",
    "citext",
    "hstore",
    "ltree",
    "lquery",
];

/// The names of the PostgreSQL types `T` can be decoded from. Types are compared by name,
/// as SQLx compares a type it only knows by name; a custom type, such as an enum declared
/// with `#[sqlx(type_name = "...")]`, adds its own name.
fn accepted_types<T: Type<Postgres>>() -> Vec<String> {
    let mut names: Vec<String> = Vec::new();
    for name in TYPE_NAMES {
        if T::compatible(&PgTypeInfo::with_name(name)) {
            names.push(name.to_string());
        }
    }
    for name in TYPE_NAMES {
        if T::compatible(&PgTypeInfo::array_of(name)) {
            names.push(format!("{name}[]"));
        }
    }
    let own = T::type_info();
    if own.oid().is_none() && !names.iter().any(|n| n.eq_ignore_ascii_case(own.name())) {
        names.push(own.name().to_string());
    }
    names
}

/// Whether a column of the type `ty` is one of the accepted types. A domain is compared as
/// its base type.
pub(crate) fn accepts(accepted: &[String], ty: &PgTypeInfo) -> bool {
    let base = match ty.kind() {
        PgTypeKind::Domain(base) => base,
        _ => ty,
    };
    accepted.iter().any(|name| name.eq_ignore_ascii_case(base.name()) || name.eq_ignore_ascii_case(ty.name()))
}

impl Description {
    /// A column decoded as `T`, with the given alias.
    pub fn column<T: Type<Postgres>>(&mut self, alias: impl Into<String>, optional: bool) {
        self.columns.push(ColumnType {
            alias: alias.into(),
            optional,
            rust_type: std::any::type_name::<T>(),
            sql_type: T::type_info().name().to_string(),
            accepts: accepted_types::<T>(),
        });
    }

    /// A child or to-one field whose values are views of type `C`.
    pub fn view<C: View>(&mut self, field_index: usize) {
        self.children.push((field_index, C::describe, None));
    }

    /// A map collection whose values are views of type `C`, keyed by `K`.
    pub fn map<K: Type<Postgres>, C: View>(&mut self, field_index: usize) {
        let mut key = Description::default();
        key.column::<K>(mabat_core::MAP_KEY_ALIAS, false);
        self.children.push((field_index, C::describe, key.columns.pop()));
    }

    /// The variant `variant` of an enum stored in a table per variant in the field
    /// `field_index`, whose columns are described by `describe`.
    pub fn variant_table(&mut self, field_index: usize, variant: &'static str, describe: DescribeFn) {
        self.variants.push((field_index, variant, describe));
    }

    pub(crate) fn variant(&self, field_index: usize, variant: &str) -> Option<DescribeFn> {
        self.variants.iter().find(|(i, v, _)| *i == field_index && *v == variant).map(|(_, _, describe)| *describe)
    }

    pub(crate) fn column_type(&self, alias: &str) -> Option<&ColumnType> {
        self.columns.iter().find(|c| c.alias == alias)
    }

    /// The describe function of a child field, and the type of its map key.
    pub(crate) fn child(&self, field_index: usize) -> Option<(DescribeFn, Option<&ColumnType>)> {
        self.children.iter().find(|(i, _, _)| *i == field_index).map(|(_, describe, key)| (*describe, key.as_ref()))
    }
}

/// A type name without module paths: `Option<String>` for
/// `core::option::Option<alloc::string::String>`.
pub(crate) fn short_type_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut segment = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' || c == ':' {
            segment.push(c);
        } else {
            out.push_str(segment.rsplit("::").next().unwrap_or(""));
            segment.clear();
            out.push(c);
        }
    }
    out.push_str(segment.rsplit("::").next().unwrap_or(""));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepted_types_by_name() {
        assert_eq!(accepted_types::<String>(), ["NAME", "TEXT", "UNKNOWN", "BPCHAR", "VARCHAR", "citext"]);
        assert_eq!(accepted_types::<i64>(), ["INT8"]);
        assert_eq!(accepted_types::<Option<i32>>(), ["INT4"]);
        assert_eq!(accepted_types::<uuid::Uuid>(), ["UUID"]);
        assert_eq!(accepted_types::<sqlx::types::Json<serde_json::Value>>(), ["JSON", "JSONB"]);
        assert_eq!(accepted_types::<Vec<i64>>(), ["INT8[]"]);
    }

    #[test]
    fn short_type_names() {
        assert_eq!(short_type_name("core::option::Option<alloc::string::String>"), "Option<String>");
        assert_eq!(short_type_name("i64"), "i64");
        assert_eq!(short_type_name("chrono::DateTime<chrono::offset::utc::Utc>"), "DateTime<Utc>");
    }
}
