//! Saving graphs: [`crate::save_graph`].
//!
//! Every entity of a graph is saved as [`crate::save`] saves a value, with its references into
//! the graph (`Ref<T>`) written as the keys of the entities they point to. So that those keys
//! exist, and so that foreign keys hold as rows are inserted, an entity is saved after the
//! entities it references: the entities are ordered by their references, and each cycle of
//! references (found with Tarjan's algorithm) is saved with its optional references NULL
//! first, then set once every entity of the cycle has its key.
//!
//! A collection of references (`Vec<Ref<T>>`) is written by where its relationship is stored:
//! through a link table, the entity's links are replaced; by a foreign key of the elements'
//! table, the elements' foreign key is written, unless the element view references the entity
//! by that same column, which then writes it and must agree with the collection.

use std::collections::{HashMap, HashSet};
use std::marker::PhantomData;

use mabat_core::shape::{Child, FieldKind, ViewShape};
use mabat_core::write::{self as statement, ColumnValue};

use crate::Error;
use crate::backend::Backend;
use crate::graph::{Arenas, Entities, shape_id};
use crate::key::{Key, KeyList};
use crate::write::{GraphRef, GraphTarget, RowWrite, ViewEncoder, Written, save_row};

/// Writing the entities of one view type of a graph, whatever the type.
trait EntityWriter<B: Backend>: Send + Sync {
    fn shape(&self) -> &'static ViewShape;
    fn count(&self, arenas: &Arenas) -> usize;
    fn write(&self, arenas: &Arenas, index: usize) -> Result<RowWrite<B>, Error>;
    fn written(&self, arenas: &mut Arenas, index: usize, written: &Written) -> Result<(), Error>;
}

struct Entity<T>(PhantomData<fn() -> T>);

impl<T: ViewEncoder<B> + Send + Sync + 'static, B: Backend> EntityWriter<B> for Entity<T> {
    fn shape(&self) -> &'static ViewShape {
        T::shape()
    }

    fn count(&self, arenas: &Arenas) -> usize {
        arenas.get(&shape_id(T::shape())).and_then(|a| a.downcast_ref::<Vec<T>>()).map_or(0, Vec::len)
    }

    fn write(&self, arenas: &Arenas, index: usize) -> Result<RowWrite<B>, Error> {
        let arena = arenas.get(&shape_id(T::shape())).and_then(|a| a.downcast_ref::<Vec<T>>());
        arena.expect("the arena of a counted entity")[index].write()
    }

    fn written(&self, arenas: &mut Arenas, index: usize, written: &Written) -> Result<(), Error> {
        let arena = arenas.get_mut(&shape_id(T::shape())).and_then(|a| a.downcast_mut::<Vec<T>>());
        arena.expect("the arena of a saved entity")[index].written(written)
    }
}

/// The view types of the entities of a graph, found from the view of its roots through its
/// references. Filled by code generated by `#[derive(View)]`.
#[doc(hidden)]
pub struct GraphTypes<B: Backend> {
    entities: Vec<Box<dyn EntityWriter<B>>>,
    seen: HashSet<usize>,
    /// Views of owned values, whose references into the graph lead to more entity types.
    owned: HashSet<usize>,
}

impl<B: Backend> GraphTypes<B> {
    fn new() -> GraphTypes<B> {
        GraphTypes { entities: Vec::new(), seen: HashSet::new(), owned: HashSet::new() }
    }

    /// `T` is a view of entities of the graph.
    pub fn entity<T: ViewEncoder<B> + Send + Sync + 'static>(&mut self) {
        if self.seen.insert(shape_id(T::shape())) {
            self.entities.push(Box::new(Entity::<T>(PhantomData)));
            T::graph_types(self);
        }
    }

    /// `T` is a view of values owned by entities, which may reference entities.
    pub fn owned<T: ViewEncoder<B>>(&mut self) {
        if self.owned.insert(shape_id(T::shape())) {
            T::graph_types(self);
        }
    }
}

/// An entity being saved.
struct Node<B: Backend> {
    /// Its view type, in [`GraphTypes::entities`].
    ty: usize,
    index: usize,
    row: Option<RowWrite<B>>,
    /// The references of its row, with the entities they point to.
    refs: Vec<(GraphRef, Option<usize>)>,
    /// Foreign keys and positions its row takes from collections of other entities, which the
    /// element view does not write itself.
    assigned: Vec<Assigned>,
    /// The entities that rows it owns reference: they must have keys before it is saved.
    owned_refs: Vec<usize>,
}

/// The foreign key of an element of a collection that writes it, with its position.
struct Assigned {
    fk: &'static str,
    /// The entity whose collection it is.
    owner: usize,
    /// The index column of the collection, and the element's position.
    index: Option<(&'static str, i64)>,
}

/// A collection of references written after every entity has its key.
struct Collection {
    owner: usize,
    child: &'static Child,
    elements: Vec<usize>,
}

/// Save the entities of a graph whose roots are views `R`, in the transaction `conn`, and
/// write generated keys and new versions back into the entities: every entity, or with
/// `changed`, those entities and the elements whose foreign key their collections write.
pub(crate) async fn save<B: Backend, R: ViewEncoder<B> + Send + Sync + 'static>(
    conn: &mut B::Connection,
    arenas: &mut Arenas,
    changed: Option<&Entities>,
) -> Result<(), Error>
where
    B::Connection: Send,
{
    let mut types = GraphTypes::<B>::new();
    types.entity::<R>();
    for id in arenas.keys() {
        if !types.seen.contains(id) {
            return Err(Error::Write {
                view: R::shape().name,
                message: "the graph has entities of a view that no reference of it leads to".to_string(),
            });
        }
    }

    // The entities, with the rows they write
    let mut nodes: Vec<Node<B>> = Vec::new();
    let mut ids: HashMap<(usize, usize), usize> = HashMap::new();
    for (ty, entity) in types.entities.iter().enumerate() {
        for index in 0..entity.count(arenas) {
            ids.insert((shape_id(entity.shape()), index), nodes.len());
            let row = entity.write(arenas, index)?;
            nodes.push(Node {
                ty,
                index,
                row: Some(row),
                refs: Vec::new(),
                assigned: Vec::new(),
                owned_refs: Vec::new(),
            });
        }
    }
    let node_of = |target: &GraphTarget, view: &'static str| {
        ids.get(&target.id()).copied().ok_or_else(|| Error::Write {
            view,
            message: format!("it references a {} that is not in the graph", (target.shape)().name),
        })
    };

    // References and collections of the rows
    let mut collections: Vec<Collection> = Vec::new();
    for (n, node) in nodes.iter_mut().enumerate() {
        let row = node.row.as_mut().expect("rows are taken when saved");
        let shape = row.shape();
        let refs = std::mem::take(&mut row.graph_refs);
        let owned_collections = std::mem::take(&mut row.graph_collections);
        let mut owned_refs = Vec::new();
        for owned in row.owned_rows_mut() {
            nested_refs(owned, &mut owned_refs);
        }
        let refs = refs
            .into_iter()
            .map(|r| {
                let target = r.target.as_ref().map(|t| node_of(t, shape.name)).transpose()?;
                Ok((r, target))
            })
            .collect::<Result<Vec<_>, Error>>()?;
        let owned_refs = owned_refs.iter().map(|t| node_of(t, shape.name)).collect::<Result<Vec<_>, _>>()?;
        for (field_index, elements) in owned_collections {
            let FieldKind::Child(child) = &shape.fields[field_index].kind else { continue };
            let elements = elements.iter().map(|t| node_of(t, shape.name)).collect::<Result<Vec<_>, _>>()?;
            collections.push(Collection { owner: n, child, elements });
        }
        node.refs = refs;
        node.owned_refs = owned_refs;
    }

    // Collections by a foreign key of the elements: the inverse of the elements' reference,
    // or written to the elements' rows
    let mut assigned_by: HashMap<(usize, &'static str), usize> = HashMap::new();
    let mut unlink = Vec::new();
    for (c, collection) in collections.iter().enumerate() {
        if collection.child.through.is_some() {
            continue;
        }
        let owner_shape = types.entities[nodes[collection.owner].ty].shape();
        let target = (collection.child.shape)();
        let inverse = target.fields.iter().any(|f| {
            matches!(&f.kind, FieldKind::ToOne { fk, graph: true, shape, .. }
                if *fk == collection.child.fk && std::ptr::eq(shape(), owner_shape))
        });
        if inverse {
            check_inverse(&nodes, &types, collection, owner_shape)?;
            continue;
        }
        for (position, &element) in collection.elements.iter().enumerate() {
            if let Some(other) = assigned_by.insert((element, collection.child.fk), collection.owner)
                && other != collection.owner
            {
                return Err(Error::Write {
                    view: owner_shape.name,
                    message: format!(
                        "a {} is an element of the collections of two entities, which its `{}` cannot both hold",
                        target.name, collection.child.fk
                    ),
                });
            }
            let index = collection.child.index.map(|column| (column, position as i64));
            nodes[element].assigned.push(Assigned { fk: collection.child.fk, owner: collection.owner, index });
        }
        unlink.push(c);
    }

    // The entities to write: the changed ones, and the elements their collections assign a
    // foreign key to. The others keep their rows, and their keys are as loaded.
    let mut write: Vec<bool> = nodes
        .iter()
        .map(|node| changed.is_none_or(|c| c.contains(&(shape_id(types.entities[node.ty].shape()), node.index))))
        .collect();
    for node in 0..nodes.len() {
        if nodes[node].assigned.iter().any(|a| write[a.owner]) {
            write[node] = true;
        }
    }
    let collections: Vec<(usize, Collection)> =
        collections.into_iter().enumerate().filter(|(_, c)| write[c.owner]).collect();
    let unlink: Vec<usize> = unlink.into_iter().filter(|c| collections.iter().any(|(i, _)| i == c)).collect();

    // The order: an entity after the entities its row needs the keys of, among those written
    let edges: Vec<Vec<(usize, bool)>> = nodes
        .iter()
        .enumerate()
        .map(|(n, node)| {
            if !write[n] {
                return Vec::new();
            }
            let refs = node.refs.iter().filter_map(|(r, target)| target.map(|t| (t, r.optional)));
            let assigned = node.assigned.iter().map(|a| (a.owner, false));
            let owned = node.owned_refs.iter().map(|t| (*t, false));
            refs.chain(assigned).chain(owned).filter(|(t, _)| write[*t]).collect()
        })
        .collect();
    let components = strongly_connected(&edges);

    let mut keys: Vec<Option<Key>> = nodes.iter().map(|n| n.row.as_ref().and_then(|r| r.row_key().cloned())).collect();
    let mut written: Vec<Option<Written>> = (0..nodes.len()).map(|_| None).collect();
    for component in components.iter().filter(|component| write[component[0]]) {
        let cyclic = component.len() > 1 || edges[component[0]].iter().any(|(t, _)| *t == component[0]);
        let inside: HashSet<usize> = component.iter().copied().collect();
        // A cycle is broken at its optional references, which are written NULL and set once the
        // cycle is saved; its entities are saved in the order of their required references
        let order = if cyclic { cycle_order(component, &edges, &nodes, &types)? } else { component.clone() };
        let mut patches = Vec::new();
        for &n in &order {
            let mut row = nodes[n].row.take().expect("each entity is saved once");
            for (r, target) in &nodes[n].refs {
                match target {
                    Some(t) if cyclic && r.optional && inside.contains(t) => {
                        row.bind_key(r.column.clone(), None)?;
                        patches.push((n, r.column.clone(), *t));
                    }
                    Some(t) => row.bind_key(r.column.clone(), Some(key_of(&keys, *t, &nodes, &types)?))?,
                    None => row.bind_key(r.column.clone(), None)?,
                }
            }
            for Assigned { fk, owner, index } in &nodes[n].assigned {
                row.bind_key((*fk).to_string(), Some(key_of(&keys, *owner, &nodes, &types)?))?;
                if let Some((column, position)) = index {
                    row.bind_key((*column).to_string(), Some(&Key::Int(*position)))?;
                }
            }
            for owned in row.owned_rows_mut() {
                resolve_nested(owned, &ids, &keys)?;
            }
            let saved = save_row::<B>(&mut *conn, row, None).await?;
            keys[n] = keys[n].take().or_else(|| saved.key().cloned());
            written[n] = Some(saved);
        }
        for (n, column, target) in patches {
            let shape = types.entities[nodes[n].ty].shape();
            let sql =
                statement::update(B::DIALECT, shape.table, shape.key_column, &[(column, ColumnValue::Bound)], None);
            let mut args = B::Arguments::default();
            let encode = |e: sqlx::error::BoxDynError| Error::Write { view: shape.name, message: e.to_string() };
            B::add_key(&mut args, key_of(&keys, target, &nodes, &types)?).map_err(encode)?;
            B::add_key(&mut args, key_of(&keys, n, &nodes, &types)?).map_err(encode)?;
            B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
        }
    }

    // Links, and the rows that are no longer elements of a collection
    for (_, collection) in &collections {
        let owner_shape = types.entities[nodes[collection.owner].ty].shape();
        let owner = key_of(&keys, collection.owner, &nodes, &types)?.clone();
        let elements =
            collection.elements.iter().map(|&e| key_of(&keys, e, &nodes, &types).cloned()).collect::<Result<_, _>>()?;
        if let Some(through) = collection.child.through {
            replace_links::<B>(&mut *conn, owner_shape, collection.child, through, owner, elements).await?;
        }
    }
    for c in unlink {
        let (_, collection) = collections.iter().find(|(i, _)| *i == c).expect("unlinked collections are kept");
        let owner = key_of(&keys, collection.owner, &nodes, &types)?.clone();
        let elements: Vec<Key> =
            collection.elements.iter().map(|&e| key_of(&keys, e, &nodes, &types).cloned()).collect::<Result<_, _>>()?;
        let target = (collection.child.shape)();
        let linked =
            crate::write::select_keys::<B>(&mut *conn, target, target.key_column, collection.child.fk, vec![owner])
                .await?;
        let gone: Vec<Key> = linked.into_iter().filter(|k| !elements.contains(k)).collect();
        set_null::<B>(&mut *conn, target, collection.child.fk, gone).await?;
    }

    // Generated keys and new versions, back into the entities
    for (n, node) in nodes.iter().enumerate() {
        if let Some(saved) = &written[n] {
            types.entities[node.ty].written(arenas, node.index, saved)?;
        }
    }
    Ok(())
}

/// The order in which to save the entities of a cycle of references, whose optional
/// references are set afterwards: an entity after those its required references point to.
/// Fails if the required references alone form a cycle.
fn cycle_order<B: Backend>(
    component: &[usize],
    edges: &[Vec<(usize, bool)>],
    nodes: &[Node<B>],
    types: &GraphTypes<B>,
) -> Result<Vec<usize>, Error> {
    let position: HashMap<usize, usize> = component.iter().enumerate().map(|(i, n)| (*n, i)).collect();
    let required: Vec<Vec<(usize, bool)>> = component
        .iter()
        .map(|n| {
            edges[*n]
                .iter()
                .filter(|(t, optional)| !optional && position.contains_key(t))
                .map(|(t, _)| (position[t], false))
                .collect()
        })
        .collect();
    let mut order = Vec::with_capacity(component.len());
    for part in strongly_connected(&required) {
        let n = component[part[0]];
        if part.len() > 1 || required[part[0]].iter().any(|(t, _)| *t == part[0]) {
            let other = component[part.get(1).copied().unwrap_or(part[0])];
            return Err(Error::Write {
                view: types.entities[nodes[n].ty].shape().name,
                message: format!(
                    "its required references form a cycle with a {}, so neither can be saved first; make one of \
                     the references an `Option`",
                    types.entities[nodes[other].ty].shape().name
                ),
            });
        }
        order.push(n);
    }
    Ok(order)
}

/// The key of a saved entity.
fn key_of<'k, B: Backend>(
    keys: &'k [Option<Key>],
    n: usize,
    nodes: &[Node<B>],
    types: &GraphTypes<B>,
) -> Result<&'k Key, Error> {
    keys[n].as_ref().ok_or_else(|| Error::Write {
        view: types.entities[nodes[n].ty].shape().name,
        message: "it has no key field, so it cannot be referenced in a write".to_string(),
    })
}

/// The entities referenced by rows owned by an entity, which cannot hold collections of
/// references themselves.
fn nested_refs<B: Backend>(row: &mut RowWrite<B>, out: &mut Vec<GraphTarget>) {
    out.extend(row.graph_refs.iter().filter_map(|r| r.target));
    for owned in row.owned_rows_mut() {
        nested_refs(owned, out);
    }
}

/// Write the references of rows owned by an entity as keys.
fn resolve_nested<B: Backend>(
    row: &mut RowWrite<B>,
    ids: &HashMap<(usize, usize), usize>,
    keys: &[Option<Key>],
) -> Result<(), Error> {
    if !row.graph_collections.is_empty() {
        return Err(Error::Write {
            view: row.shape().name,
            message: "collections of references into a graph (`Vec<Ref<T>>`) are saved on the entities of the graph, \
                      not on the values they own"
                .to_string(),
        });
    }
    for r in std::mem::take(&mut row.graph_refs) {
        let key = match &r.target {
            Some(target) => {
                let n = ids[&target.id()];
                Some(keys[n].clone().ok_or_else(|| Error::Write {
                    view: (target.shape)().name,
                    message: "it has no key field, so it cannot be referenced in a write".to_string(),
                })?)
            }
            None => None,
        };
        row.bind_key(r.column, key.as_ref())?;
    }
    for owned in row.owned_rows_mut() {
        resolve_nested(owned, ids, keys)?;
    }
    Ok(())
}

/// A collection that is the inverse of its elements' reference must agree with it: each
/// element references the owner, and each entity that references the owner is an element.
fn check_inverse<B: Backend>(
    nodes: &[Node<B>],
    types: &GraphTypes<B>,
    collection: &Collection,
    owner_shape: &'static ViewShape,
) -> Result<(), Error> {
    let fk = collection.child.fk;
    let points_to = |n: usize| nodes[n].refs.iter().find(|(r, _)| r.column == fk).and_then(|(_, t)| *t);
    let target = (collection.child.shape)();
    let disagree = |what: &str| Error::Write {
        view: owner_shape.name,
        message: format!(
            "a {} {what}: a collection by `{fk}` and the elements' reference by `{fk}` describe one relationship, \
             and must agree",
            target.name
        ),
    };
    for &element in &collection.elements {
        if points_to(element) != Some(collection.owner) {
            return Err(disagree("is an element of its collection but does not reference it"));
        }
    }
    for (n, node) in nodes.iter().enumerate() {
        if std::ptr::eq(types.entities[node.ty].shape(), target)
            && points_to(n) == Some(collection.owner)
            && !collection.elements.contains(&n)
        {
            return Err(disagree("references it but is not an element of its collection"));
        }
    }
    Ok(())
}

/// Replace the links of an entity in the link table of a collection.
async fn replace_links<B: Backend>(
    conn: &mut B::Connection,
    shape: &'static ViewShape,
    child: &Child,
    through: mabat_core::shape::Through,
    owner: Key,
    elements: Vec<Key>,
) -> Result<(), Error> {
    let encode = |e: sqlx::error::BoxDynError| Error::Write { view: shape.name, message: e.to_string() };
    let sql = statement::delete_by(B::DIALECT, through.table, child.fk, 1);
    let mut args = B::Arguments::default();
    B::add_keys(&mut args, &KeyList::new(vec![owner.clone()]).map_err(|_| encode("mixed keys".into()))?)
        .map_err(encode)?;
    B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
    for (position, element) in elements.into_iter().enumerate() {
        let mut args = B::Arguments::default();
        let mut columns =
            vec![(child.fk.to_string(), ColumnValue::Bound), (through.target.to_string(), ColumnValue::Bound)];
        B::add_key(&mut args, &owner).map_err(encode)?;
        B::add_key(&mut args, &element).map_err(encode)?;
        if let Some(column) = child.index {
            B::add_key(&mut args, &Key::Int(position as i64)).map_err(encode)?;
            columns.push((column.to_string(), ColumnValue::Bound));
        }
        let sql = statement::insert(B::DIALECT, through.table, &columns);
        B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
    }
    Ok(())
}

/// Set `column` to NULL in the rows of `shape` with the keys: rows no longer in a collection.
async fn set_null<B: Backend>(
    conn: &mut B::Connection,
    shape: &'static ViewShape,
    column: &str,
    keys: Vec<Key>,
) -> Result<(), Error> {
    let Ok(keys) = KeyList::new(keys) else { return Ok(()) };
    for keys in keys.chunks(crate::write::MAX_KEYS) {
        let sql = statement::set_null_by(B::DIALECT, shape.table, column, shape.key_column, keys.len());
        let mut args = B::Arguments::default();
        B::add_keys(&mut args, &keys).map_err(|e| Error::Write { view: shape.name, message: e.to_string() })?;
        B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
    }
    Ok(())
}

fn query_error(shape: &ViewShape, sql: &str, source: sqlx::Error) -> Error {
    Error::Query { view: shape.name, path: String::new(), sql: sql.to_string(), source }
}

/// The strongly connected components of a graph given by its edges, with Tarjan's
/// algorithm: each component comes after the components its edges lead to.
fn strongly_connected(edges: &[Vec<(usize, bool)>]) -> Vec<Vec<usize>> {
    struct State<'e> {
        edges: &'e [Vec<(usize, bool)>],
        next: usize,
        index: Vec<Option<usize>>,
        low: Vec<usize>,
        stack: Vec<usize>,
        on_stack: Vec<bool>,
        components: Vec<Vec<usize>>,
    }

    fn visit(state: &mut State<'_>, v: usize) {
        state.index[v] = Some(state.next);
        state.low[v] = state.next;
        state.next += 1;
        state.stack.push(v);
        state.on_stack[v] = true;
        for &(w, _) in &state.edges[v] {
            match state.index[w] {
                None => {
                    visit(state, w);
                    state.low[v] = state.low[v].min(state.low[w]);
                }
                Some(index) if state.on_stack[w] => state.low[v] = state.low[v].min(index),
                Some(_) => {}
            }
        }
        if Some(state.low[v]) == state.index[v] {
            let mut component = Vec::new();
            loop {
                let w = state.stack.pop().expect("v is on the stack");
                state.on_stack[w] = false;
                component.push(w);
                if w == v {
                    break;
                }
            }
            component.reverse();
            state.components.push(component);
        }
    }

    let n = edges.len();
    let mut state = State {
        edges,
        next: 0,
        index: vec![None; n],
        low: vec![0; n],
        stack: Vec::new(),
        on_stack: vec![false; n],
        components: Vec::new(),
    };
    for v in 0..n {
        if state.index[v].is_none() {
            visit(&mut state, v);
        }
    }
    state.components
}

#[cfg(test)]
mod tests {
    use super::strongly_connected;

    #[test]
    fn components_come_after_what_they_reference() {
        // 0 → 1 → 2, 2 → 1 (a cycle), 3 → 0
        let edges = vec![vec![(1, false)], vec![(2, false)], vec![(1, true)], vec![(0, false)]];
        let components = strongly_connected(&edges);
        assert_eq!(components, vec![vec![1, 2], vec![0], vec![3]]);
    }

    #[test]
    fn a_self_reference_is_its_own_component() {
        let edges = vec![vec![(0, true)], vec![]];
        assert_eq!(strongly_connected(&edges), vec![vec![0], vec![1]]);
    }
}
