//! Decoding views as JSON, for [`crate::Load::json`].
//!
//! The code generated by `#[derive(View)]` decodes each selected field as JSON with the
//! helpers here: a column with its Rust type's `Serialize` implementation, a `#[view(json)]`
//! column as the JSON it holds, collections as arrays, maps as objects, references as
//! objects or `null`, and enums as objects with a `__typename` field naming the variant.

use std::collections::{HashMap, HashSet};
use std::marker::PhantomData;

use mabat_core::{KEY_ALIAS, MAP_KEY_ALIAS};
use serde_json::{Map, Value};
use sqlx::{Decode, Type};

use crate::backend::Backend;
use crate::key::Key;
use crate::node::{Node, optional_column};
use crate::{Error, ViewDecoder};

/// The field of a JSON object that names the variant of an enum, as GraphQL names types.
pub const TYPENAME: &str = "__typename";

/// The JSON name of a field: its name, or `_0`, `_1`, … for a tuple field.
#[doc(hidden)]
pub fn field_name(name: &str) -> String {
    if name.starts_with(|c: char| c.is_ascii_digit()) { format!("_{name}") } else { name.to_string() }
}

/// Selects how a column of type `T` is decoded as JSON: through `Serialize` if `T`
/// implements it, else as an error when it is loaded. Generated code calls
/// `(&JsonProbe::<T, B>::NEW).json_column(..)` with both traits in scope; method resolution
/// prefers [`JsonViaSerialize`], which needs no auto-ref, when it applies.
#[doc(hidden)]
pub struct JsonProbe<T, B>(PhantomData<fn() -> (T, B)>);

impl<T, B> JsonProbe<T, B> {
    pub const NEW: JsonProbe<T, B> = JsonProbe(PhantomData);
}

#[doc(hidden)]
pub trait JsonViaSerialize<B: Backend> {
    fn json_column(&self, row: &B::Row, node: &Node<B>, alias: &str) -> Result<Value, Error>;
}

impl<T, B: Backend> JsonViaSerialize<B> for JsonProbe<T, B>
where
    T: serde::Serialize + for<'r> Decode<'r, B> + Type<B>,
{
    fn json_column(&self, row: &B::Row, node: &Node<B>, alias: &str) -> Result<Value, Error> {
        let value = optional_column::<T, B>(row, node, alias)?;
        serde_json::to_value(value).map_err(|e| node.json_error(alias, e.to_string()))
    }
}

#[doc(hidden)]
pub trait JsonFallback<B: Backend> {
    fn json_column(&self, row: &B::Row, node: &Node<B>, alias: &str) -> Result<Value, Error>;
}

impl<T, B: Backend> JsonFallback<B> for &JsonProbe<T, B> {
    fn json_column(&self, _: &B::Row, node: &Node<B>, alias: &str) -> Result<Value, Error> {
        let ty = std::any::type_name::<T>();
        Err(node.json_error(alias, format!("{ty} does not implement serde::Serialize")))
    }
}

/// A `#[view(json)]` column, as the JSON it holds.
#[doc(hidden)]
pub fn json_raw<B: Backend>(row: &B::Row, node: &Node<B>, alias: &str) -> Result<Value, Error>
where
    sqlx::types::Json<Value>: for<'r> Decode<'r, B> + Type<B>,
{
    Ok(optional_column::<sqlx::types::Json<Value>, B>(row, node, alias)?.map_or(Value::Null, |json| json.0))
}

/// The elements of a to-many collection of the row, as an array.
#[doc(hidden)]
pub fn json_children<C: ViewDecoder<B>, B: Backend>(
    row: &B::Row,
    node: &Node<B>,
    field_index: usize,
) -> Result<Value, Error> {
    if node.graph_edge(field_index) {
        let keys = node.edge_keys(row, field_index)?;
        return Ok(Value::Array(keys.iter().map(|key| reference(C::shape().name, key)).collect()));
    }
    let elements = node.child_rows(row, field_index, KEY_ALIAS)?;
    elements.into_iter().map(|(row, child)| C::decode_json(row, child)).collect::<Result<_, _>>().map(Value::Array)
}

/// The elements of a map collection of the row, as an object keyed by their map keys.
/// `key` decodes a map key as JSON; keys that are not strings are written as JSON text.
#[doc(hidden)]
pub fn json_map<C: ViewDecoder<B>, B: Backend>(
    row: &B::Row,
    node: &Node<B>,
    field_index: usize,
    key: impl Fn(&B::Row, &Node<B>, &str) -> Result<Value, Error>,
) -> Result<Value, Error> {
    let mut map = Map::new();
    for (row, child) in node.child_rows(row, field_index, KEY_ALIAS)? {
        let key = match key(row, child, MAP_KEY_ALIAS)? {
            Value::String(key) => key,
            other => other.to_string(),
        };
        if map.insert(key, C::decode_json(row, child)?).is_some() {
            return Err(Error::DuplicateMapKey { view: child.view(), path: child.path().to_string() });
        }
    }
    Ok(Value::Object(map))
}

/// A to-one reference of the row, as an object, or `null` if its foreign key is NULL.
#[doc(hidden)]
pub fn json_to_one<C: ViewDecoder<B>, B: Backend>(
    row: &B::Row,
    node: &Node<B>,
    field_index: usize,
    ref_alias: &str,
    optional: bool,
) -> Result<Value, Error> {
    if node.graph_edge(field_index) {
        return Ok(match node.key(row, ref_alias)? {
            Some(key) => reference(C::shape().name, &key),
            None if optional => Value::Null,
            None => return Err(node.missing_reference(field_index, ref_alias)),
        });
    }
    match node.referenced(row, field_index, ref_alias)? {
        Some((_, (row, child))) => C::decode_json(row, child),
        None if optional => Ok(Value::Null),
        None => Err(node.missing_reference(field_index, ref_alias)),
    }
}

/// An object with the fields of a view or a variant, and the name of the variant.
#[doc(hidden)]
pub fn json_object(typename: Option<&str>, fields: Vec<(String, Value)>) -> Value {
    let mut map = Map::new();
    if let Some(typename) = typename {
        map.insert(TYPENAME.to_string(), Value::String(typename.to_string()));
    }
    map.extend(fields);
    Value::Object(map)
}

/// Add the fields of the object `from` to the object `to`, for the row of a variant table.
#[doc(hidden)]
pub fn json_merge(mut to: Value, from: Value) -> Value {
    if let (Value::Object(to), Value::Object(from)) = (&mut to, from) {
        to.extend(from);
    }
    to
}

/// The member naming an entity of a graph written as JSON, see [`crate::Load::graph_json`].
pub(crate) const ID: &str = "$id";
/// The member of an object that stands for an entity written elsewhere.
pub(crate) const REF: &str = "$ref";

/// The `$id` of an entity: its view and key, such as `Employee:2`.
pub(crate) fn entity_id(view: &str, key: &Key) -> String {
    match key {
        Key::Int(key) => format!("{view}:{key}"),
        Key::Text(key) => format!("{view}:{key}"),
        Key::Uuid(key) => format!("{view}:{key}"),
    }
}

/// A reference to an entity: `{"$ref": "Employee:2"}`.
fn reference(view: &str, key: &Key) -> Value {
    let mut object = Map::new();
    object.insert(REF.to_string(), Value::String(entity_id(view, key)));
    Value::Object(object)
}

/// The roots of a graph as JSON, each entity written once: the first time it is reached from the
/// roots, depth first, as its object with its `$id`, and everywhere else as `{"$ref": id}`.
pub(crate) fn inline_graph(roots: &[String], objects: &HashMap<String, Value>) -> Value {
    fn expand(value: &Value, objects: &HashMap<String, Value>, written: &mut HashSet<String>) -> Value {
        match value {
            Value::Object(fields) if fields.len() == 1 => match fields.get(REF) {
                Some(Value::String(id)) if objects.contains_key(id) && written.insert(id.clone()) => {
                    expand(&objects[id], objects, written)
                }
                _ => value.clone(),
            },
            Value::Object(fields) => Value::Object(
                fields.iter().map(|(name, value)| (name.clone(), expand(value, objects, written))).collect(),
            ),
            Value::Array(values) => Value::Array(values.iter().map(|value| expand(value, objects, written)).collect()),
            _ => value.clone(),
        }
    }
    let mut written = HashSet::new();
    let roots = roots.iter().map(|id| {
        let mut object = Map::new();
        object.insert(REF.to_string(), Value::String(id.clone()));
        expand(&Value::Object(object), objects, &mut written)
    });
    Value::Array(roots.collect())
}
