//! Snapshots of a database's schema, for checking views without a database: see
//! [`mabat_check::Snapshot`].

use std::collections::HashMap;
use std::path::PathBuf;

pub use mabat_check::{Column, ForeignKey, Snapshot, Table};
use mabat_core::TAG_ALIAS;

use crate::Error;
use crate::backend::{Backend, Conn};
use crate::check;
use crate::manifest::{ColumnManifest, LinkManifest, Manifest, QueryManifest, Role, ViewManifest};
use crate::overrides::OverrideFile;
use crate::registry;
use crate::report::{Diagnostic, Report, Severity, suggest};

/// A snapshot of the tables and views of the database's current schema: their columns, with
/// their types as the database declares them and as SQLx names them, nullability and generated
/// values, and their primary and foreign keys.
pub async fn snapshot<C: Conn>(conn: &mut C) -> Result<Snapshot, Error> {
    let mut conn = conn.source().single().await?;
    let mut tables = C::Backend::read_catalog(&mut conn).await.map_err(Error::Check)?;
    for table in &mut tables {
        // The types SQLx reads the columns as, which the manifest's accepted types name
        let sql = format!("SELECT * FROM {}", C::Backend::DIALECT.quote(&table.name));
        let inspected = C::Backend::inspect(&mut conn, sql).await.map_err(Error::Check)?;
        for column in &mut table.columns {
            let found = inspected.as_ref().ok().and_then(|i| i.columns.iter().find(|c| c.name == column.name));
            column.r#type = found.and_then(|c| c.type_name.clone()).unwrap_or_else(|| column.declared.to_uppercase());
        }
    }
    Ok(Snapshot::new(<C::Backend as sqlx::Database>::NAME, tables))
}

impl Manifest {
    /// Check the views against a snapshot of the schema, without a database: that the tables
    /// and columns the queries read exist (M0201, M0202), that the columns have types the fields
    /// can be decoded from (M0203) and are not nullable under fields that are not `Option`
    /// (M0204, a warning), that the columns linking queries hold the same kind of key (M0205),
    /// that each key is the primary key of its table (M0206, a warning), and that generated keys
    /// are generated by the database (M0207).
    ///
    /// The override files of the directories are read and checked for their names only (M0100,
    /// M0101): their SQL needs a database to prepare it, `mabat check --database-url`. `origin`
    /// names the snapshot in the diagnostics, e.g. `mabat/schema.json`.
    pub fn check_snapshot(&self, snapshot: &Snapshot, origin: &str, overrides: &[PathBuf]) -> Result<Report, String> {
        if self.backend != snapshot.backend {
            return Err(format!("the manifest is for {}, the snapshot is of {}", self.backend, snapshot.backend));
        }
        if self.views.iter().flat_map(|v| &v.queries).any(|q| q.table.is_empty()) {
            return Err("the manifest does not name the tables of its queries: write it again with this version of \
                        Mabat"
                .to_string());
        }
        let mut report = Report::default();
        let files = registry::read_override_files(overrides, &[], &mut report);
        let mut files: HashMap<String, OverrideFile> = files.into_iter().map(|f| (f.view.clone(), f)).collect();
        for view in &self.views {
            let file = files.remove(&view.name);
            check::queries_of(view, file.as_ref(), &mut report);
            for query in &view.queries {
                let context = SchemaCheck { snapshot, origin, view, query };
                context.check(&mut report);
            }
        }
        check::unknown_views(self, files.into_values(), &mut report);
        Ok(report)
    }
}

/// A query of a view, checked against a snapshot.
struct SchemaCheck<'a> {
    snapshot: &'a Snapshot,
    origin: &'a str,
    view: &'a ViewManifest,
    query: &'a QueryManifest,
}

impl SchemaCheck<'_> {
    fn check(&self, report: &mut Report) {
        let query = self.query;
        let Some(table) = self.table(&query.table, report) else { return };
        let through = match &query.link {
            LinkManifest::Child { through: Some(through), .. } => self.table(&through.table, report),
            _ => None,
        };

        let key = self.column(table, &query.key_column, report);
        if let Some(key) = key {
            self.check_key(table, key, report);
        }
        for column in &query.columns {
            let in_table = if column.link_table { through } else { Some(table) };
            if column.column.is_empty() || column.role == Role::Key {
                continue;
            }
            let Some(in_table) = in_table else { continue };
            if let Some(found) = self.column(in_table, &column.column, report) {
                self.check_column(in_table, column, found, report);
            }
        }
        self.check_link(table, through, key, report);
    }

    /// The table the query reads, or M0201.
    fn table(&self, name: &str, report: &mut Report) -> Option<&Table> {
        let found = self.snapshot.table(name);
        if found.is_none() {
            let mut notes = Vec::new();
            if let Some(similar) = suggest(name, self.snapshot.tables.iter().map(|t| t.name.as_str())) {
                notes.push(format!("did you mean `{similar}`?"));
            }
            self.push(report, Severity::Error, "M0201", format!("table `{name}` is not in the schema"), notes);
        }
        found
    }

    /// The column of the table, or M0202.
    fn column<'t>(&self, table: &'t Table, name: &str, report: &mut Report) -> Option<&'t Column> {
        let found = find(table, name);
        if found.is_none() {
            let mut notes = Vec::new();
            if let Some(similar) = suggest(name, table.columns.iter().map(|c| c.name.as_str())) {
                notes.push(format!("did you mean `{similar}`?"));
            }
            let summary = format!("column `{}.{name}` is not in the schema", table.name);
            self.push(report, Severity::Error, "M0202", summary, notes);
        }
        found
    }

    /// The type and nullability of a column a path is decoded from (M0203, M0204).
    fn check_column(&self, table: &Table, selected: &ColumnManifest, column: &Column, report: &mut Report) {
        let Some(ty) = &selected.r#type else { return };
        let path = format!("path \"{}\"", selected.alias);
        let name = format!("`{}.{}`", table.name, column.name);
        // A tag is selected as text, whatever the type of its column
        let tag = selected.alias.ends_with(TAG_ALIAS);
        if !tag && !column.r#type.is_empty() && !ty.accepts.iter().any(|a| a.eq_ignore_ascii_case(&column.r#type)) {
            let summary = format!("{path} is {}, which cannot be decoded from column {name}", ty.rust);
            let notes = vec![
                format!("the column is {} ({})", column.declared, column.r#type),
                format!("{} is decoded from {}", ty.rust, ty.accepts.join(", ")),
            ];
            self.push(report, Severity::Error, "M0203", summary, notes);
        }
        // Fields of embedded values and enums may be NULL in rows that do not hold them, and the
        // columns of views of the database are reported nullable whatever they select
        let top_level = !selected.alias.contains('.');
        if column.nullable && !selected.optional && selected.role == Role::Field && top_level && !table.view && !tag {
            let summary = format!("{path} is {}, but column {name} is nullable", ty.rust);
            let notes = vec!["a NULL fails the load: make the field an Option, or the column NOT NULL".to_string()];
            self.push(report, Severity::Warning, "M0204", summary, notes);
        }
    }

    /// The key of the query is the primary key of its table (M0206), and generated if the view
    /// says so (M0207).
    fn check_key(&self, table: &Table, key: &Column, report: &mut Report) {
        let name = format!("`{}.{}`", table.name, key.name);
        if !table.view && !table.primary_key.is_empty() && table.primary_key != [key.name.as_str()] {
            let summary = format!("the key of {}, {name}, is not the primary key of `{}`", self.query.view, table.name);
            let notes = vec![
                format!("the primary key is ({})", table.primary_key.join(", ")),
                "loads assume the key is unique, and saves update and upsert by it".to_string(),
            ];
            self.push(report, Severity::Warning, "M0206", summary, notes);
        }
        if self.query.generated && !key.generated {
            let summary =
                format!("the key of {} is generated, but the database does not generate {name}", self.query.view);
            let notes = vec![
                "an insert would leave the key to the database: declare the column as an identity, serial or \
                 AUTO_INCREMENT column, or remove #[view(generated)]"
                    .to_string(),
            ];
            self.push(report, Severity::Error, "M0207", summary, notes);
        }
    }

    /// The columns that link the query to its parent hold the same kind of key as the columns
    /// they match (M0205).
    fn check_link(&self, table: &Table, through: Option<&Table>, key: Option<&Column>, report: &mut Report) {
        let Some(parent) = self.query.parent.map(|p| &self.view.queries[p]) else { return };
        let Some(parent_table) = self.snapshot.table(&parent.table) else { return };
        let parent_key = || find(parent_table, &parent.key_column);
        let mut pairs = Vec::new();
        match &self.query.link {
            LinkManifest::Root => {}
            LinkManifest::Child { fk, through: None } => {
                pairs.push(((table, find(table, fk)), (parent_table, parent_key())));
            }
            LinkManifest::Child { fk, through: Some(link) } => {
                if let Some(through) = through {
                    pairs.push(((through, find(through, fk)), (parent_table, parent_key())));
                    pairs.push(((through, find(through, &link.target)), (table, key)));
                }
            }
            LinkManifest::ToOne { ref_alias } => {
                let reference = parent.columns.iter().find(|c| &c.alias == ref_alias);
                let column = reference.and_then(|c| find(parent_table, &c.column));
                pairs.push(((parent_table, column), (table, key)));
            }
            LinkManifest::Variant { .. } => pairs.push(((table, key), (parent_table, parent_key()))),
        }
        for ((table, column), (target_table, target)) in pairs {
            let (Some(column), Some(target)) = (column, target) else { continue };
            let (Some(class), Some(target_class)) = (key_class(column), key_class(target)) else { continue };
            if class != target_class {
                let summary = format!(
                    "{} links `{}.{}` to `{}.{}`, which hold different kinds of key",
                    self.query_name(),
                    table.name,
                    column.name,
                    target_table.name,
                    target.name
                );
                let notes = vec![format!(
                    "`{}.{}` is {} ({}), `{}.{}` is {} ({})",
                    table.name,
                    column.name,
                    column.declared,
                    class,
                    target_table.name,
                    target.name,
                    target.declared,
                    target_class
                )];
                self.push(report, Severity::Error, "M0205", summary, notes);
            }
        }
    }

    fn query_name(&self) -> String {
        format!("{}.{}", self.view.name, self.query.name)
    }

    fn push(&self, report: &mut Report, severity: Severity, code: &'static str, summary: String, notes: Vec<String>) {
        let diagnostic = Diagnostic {
            severity,
            code,
            view: self.view.name.clone(),
            query: self.query.name.clone(),
            origin: Some(self.origin.to_string()),
            summary: format!("{}: {summary}", self.query_name()),
            notes,
        };
        // A table or column read by several queries of a view is reported once
        let problem = |d: &Diagnostic| d.summary.split_once(": ").map(|(_, problem)| problem.to_string());
        let repeated = report
            .diagnostics
            .iter()
            .any(|d| d.view == diagnostic.view && d.code == diagnostic.code && problem(d) == problem(&diagnostic));
        if !repeated {
            report.push(diagnostic);
        }
    }
}

/// The column of the table with the name: as written, else ignoring case, as databases that
/// fold unquoted names do.
fn find<'t>(table: &'t Table, name: &str) -> Option<&'t Column> {
    table
        .columns
        .iter()
        .find(|c| c.name == name)
        .or_else(|| table.columns.iter().find(|c| c.name.eq_ignore_ascii_case(name)))
}

/// The kind of key a column can hold, from its type: `None` for a type that holds no key.
fn key_class(column: &Column) -> Option<&'static str> {
    let ty = column.r#type.to_ascii_lowercase();
    let declared = column.declared.to_ascii_lowercase();
    let is = |names: &[&str]| names.iter().any(|n| ty.contains(n) || declared.contains(n));
    if is(&["uuid"]) {
        Some("a uuid")
    } else if is(&["int", "serial"]) {
        Some("an integer")
    } else if is(&["char", "text", "name", "citext"]) {
        Some("a text")
    } else {
        None
    }
}
