//! Writing aggregates: [`crate::save`] and [`crate::delete`].
//!
//! The code generated by `#[derive(View)]` turns a value into a [`RowWrite`]: the columns of
//! its row, with the rows of its owned collections, the links of its many-to-many
//! collections and the rows of its variant tables. Saving it upserts the row, then makes
//! each collection, link table and variant table match the value.

use std::marker::PhantomData;

use mabat_core::shape::{EmbeddedKind, EmbeddedShape, FieldKind, VariantData, ViewShape};
use mabat_core::write::{self as statement, ColumnValue};
use sqlx::{Arguments, Encode, Type};

use crate::backend::{Backend, BoxFuture};
use crate::key::{Key, KeyList};
use crate::{Error, ViewDecoder};

/// The most keys of one statement.
const MAX_KEYS: usize = 1000;

/// The row of a value to write, with what it owns. Also a link of a many-to-many
/// collection, whose key is the key of the linked value.
pub struct RowWrite<B: Backend> {
    shape: &'static ViewShape,
    key: Option<Key>,
    columns: Vec<(String, ColumnValue)>,
    args: B::Arguments,
    /// Owned collections: the field and the rows of its elements, in order.
    collections: Vec<(usize, Vec<RowWrite<B>>)>,
    /// Many-to-many collections: the field and its links, in order.
    links: Vec<(usize, Vec<RowWrite<B>>)>,
    /// Enums stored in a table per variant: the field, the variant, and its row.
    variants: Vec<(usize, &'static str, Option<RowWrite<B>>)>,
}

impl<B: Backend> RowWrite<B> {
    #[doc(hidden)]
    pub fn new(shape: &'static ViewShape) -> RowWrite<B> {
        RowWrite {
            shape,
            key: None,
            columns: Vec::new(),
            args: B::Arguments::default(),
            collections: Vec::new(),
            links: Vec::new(),
            variants: Vec::new(),
        }
    }

    fn error(&self, message: String) -> Error {
        Error::Write { view: self.shape.name, message }
    }

    /// Bind a value to a column.
    #[doc(hidden)]
    pub fn bind<'t, T>(&mut self, column: String, value: T) -> Result<(), Error>
    where
        T: Encode<'t, B> + Type<B>,
    {
        self.args.add(value).map_err(|e| self.error(format!("cannot encode `{column}`: {e}")))?;
        self.columns.push((column, ColumnValue::Bound));
        Ok(())
    }

    /// Write NULL to a column.
    #[doc(hidden)]
    pub fn null(&mut self, column: String) {
        self.columns.push((column, ColumnValue::Null));
    }

    /// Write a string literal to a column: the tag of an enum.
    #[doc(hidden)]
    pub fn literal(&mut self, column: String, text: &str) {
        self.columns.push((column, ColumnValue::Literal(text.to_string())));
    }

    #[doc(hidden)]
    pub fn set_key(&mut self, key: Option<Key>) {
        self.key = key;
    }

    /// Write the foreign key of a to-one reference: the key of the referenced value, or NULL.
    #[doc(hidden)]
    pub fn reference(&mut self, fk: &str, key: Option<Key>) -> Result<(), Error> {
        match key {
            Some(key) => {
                B::add_key(&mut self.args, &key).map_err(|e| self.error(format!("cannot encode `{fk}`: {e}")))?;
                self.columns.push((fk.to_string(), ColumnValue::Bound));
            }
            None => self.null(fk.to_string()),
        }
        Ok(())
    }

    /// The elements of an owned collection, in order.
    #[doc(hidden)]
    pub fn collection(&mut self, field_index: usize, rows: Vec<RowWrite<B>>) {
        self.collections.push((field_index, rows));
    }

    /// The links of a many-to-many collection, in order.
    #[doc(hidden)]
    pub fn links(&mut self, field_index: usize, links: Vec<RowWrite<B>>) {
        self.links.push((field_index, links));
    }

    /// The variant of an enum stored in a table per variant, with its row if it has data.
    #[doc(hidden)]
    pub fn variant(&mut self, field_index: usize, variant: &'static str, row: Option<RowWrite<B>>) {
        self.variants.push((field_index, variant, row));
    }

    /// Write NULL to the columns of the variants other than `chosen` of an enum stored in
    /// columns under `prefix`, unless the chosen variant writes them too.
    #[doc(hidden)]
    pub fn null_other_variants(&mut self, shape: &'static EmbeddedShape, prefix: &str, chosen: &str) {
        let EmbeddedKind::Sum(sum) = &shape.kind else { return };
        let mut columns = Vec::new();
        for variant in sum.variants.iter().filter(|v| v.name != chosen) {
            if let VariantData::Columns { fields } = &variant.data {
                columns_of(fields, prefix, &mut columns);
            }
        }
        for column in columns {
            if !self.columns.iter().any(|(c, _)| *c == column) {
                self.null(column);
            }
        }
    }
}

/// The columns of fields stored in a row under `prefix`, with those of embedded values.
fn columns_of(fields: &'static [mabat_core::Field], prefix: &str, out: &mut Vec<String>) {
    for field in fields {
        match &field.kind {
            FieldKind::Column { column, .. } => out.push(format!("{prefix}{column}")),
            FieldKind::Embedded { column_prefix, shape } => match &shape().kind {
                EmbeddedKind::Product { fields } => columns_of(fields, &format!("{prefix}{column_prefix}"), out),
                EmbeddedKind::Sum(sum) => {
                    let prefix = format!("{prefix}{column_prefix}");
                    out.push(format!("{prefix}{}", sum.tag_column));
                    for variant in sum.variants {
                        if let VariantData::Columns { fields } = &variant.data {
                            columns_of(fields, &prefix, out);
                        }
                    }
                }
            },
            FieldKind::Child(_) | FieldKind::ToOne { .. } => {}
        }
    }
}

/// Writing a value as an aggregate. Implemented by `#[derive(View)]` for each database
/// whose feature is enabled.
pub trait ViewEncoder<B: Backend>: ViewDecoder<B> {
    /// The key of the value: its key field, `None` if the view has none.
    fn key(&self) -> Option<Key>;

    /// The row of the value, with what it owns.
    fn write(&self) -> Result<RowWrite<B>, Error>;
}

/// Writing an embedded value to the row of the value that contains it.
pub trait EmbeddedEncoder<B: Backend>: crate::EmbeddedDecoder<B> {
    /// Write the columns, whose names start with `prefix`. `field_index` is the index of the
    /// view's field that holds the value, for variant tables.
    fn write_embedded(&self, row: &mut RowWrite<B>, prefix: &str, field_index: usize) -> Result<(), Error>;
}

/// The shape of the table of a variant of an enum stored in a table per variant.
#[doc(hidden)]
pub fn variant_table(shape: &'static EmbeddedShape, variant: &str) -> &'static ViewShape {
    let EmbeddedKind::Sum(sum) = &shape.kind else { unreachable!("{} is not an enum", shape.name) };
    match sum.variants.iter().find(|v| v.name == variant).map(|v| &v.data) {
        Some(VariantData::Table { shape }) => shape(),
        _ => unreachable!("{}::{variant} has no table", shape.name),
    }
}

/// The key of a referenced or linked value, which needs a key field.
#[doc(hidden)]
pub fn target_key<T: ViewEncoder<B>, B: Backend>(value: &T) -> Result<Key, Error> {
    value.key().ok_or_else(|| Error::Write {
        view: T::shape().name,
        message: "it has no key field, so it cannot be referenced in a write".to_string(),
    })
}

/// Selects how a column of type `T` is written: through `Encode` if `T` implements it,
/// else as an error when it is saved. See [`crate::json::JsonProbe`] for the technique.
#[doc(hidden)]
pub struct WriteProbe<T, B>(PhantomData<fn() -> (T, B)>);

impl<T, B> WriteProbe<T, B> {
    pub const NEW: WriteProbe<T, B> = WriteProbe(PhantomData);
}

#[doc(hidden)]
pub trait WriteViaEncode<T, B: Backend> {
    fn write_column(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> WriteViaEncode<T, B> for WriteProbe<T, B>
where
    T: for<'t> Encode<'t, B> + Type<B>,
{
    fn write_column(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error> {
        row.bind(column, value)
    }
}

#[doc(hidden)]
pub trait WriteFallback<T, B: Backend> {
    fn write_column(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> WriteFallback<T, B> for &WriteProbe<T, B> {
    fn write_column(&self, row: &mut RowWrite<B>, column: String, _: &T) -> Result<(), Error> {
        let ty = std::any::type_name::<T>();
        Err(row.error(format!("`{column}` cannot be written: {ty} does not implement sqlx::Encode")))
    }
}

/// Selects how a `#[view(json)]` column of type `T` is written: as JSON through `Serialize`
/// if `T` implements it, else as an error when it is saved.
#[doc(hidden)]
pub struct JsonWriteProbe<T, B>(PhantomData<fn() -> (T, B)>);

impl<T, B> JsonWriteProbe<T, B> {
    pub const NEW: JsonWriteProbe<T, B> = JsonWriteProbe(PhantomData);
}

#[doc(hidden)]
pub trait JsonWriteViaSerialize<T, B: Backend> {
    fn write_json(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> JsonWriteViaSerialize<T, B> for JsonWriteProbe<T, B>
where
    T: serde::Serialize,
    sqlx::types::Json<serde_json::Value>: for<'t> Encode<'t, B> + Type<B>,
{
    fn write_json(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error> {
        let json = serde_json::to_value(value).map_err(|e| row.error(format!("cannot write `{column}`: {e}")))?;
        // `None` is NULL, not the JSON `null`
        if json.is_null() {
            row.null(column);
            return Ok(());
        }
        row.bind(column, sqlx::types::Json(json))
    }
}

#[doc(hidden)]
pub trait JsonWriteFallback<T, B: Backend> {
    fn write_json(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> JsonWriteFallback<T, B> for &JsonWriteProbe<T, B> {
    fn write_json(&self, row: &mut RowWrite<B>, column: String, _: &T) -> Result<(), Error> {
        let ty = std::any::type_name::<T>();
        Err(row.error(format!("`{column}` cannot be written: {ty} does not implement serde::Serialize")))
    }
}

/// Selects how the key field of type `T` becomes a [`Key`]: with `Into<Key>` if `T`
/// implements it, else `None`.
#[doc(hidden)]
pub struct KeyProbe<T>(PhantomData<fn() -> T>);

impl<T> KeyProbe<T> {
    pub const NEW: KeyProbe<T> = KeyProbe(PhantomData);
}

#[doc(hidden)]
pub trait KeyViaInto<T> {
    fn key(&self, value: &T) -> Option<Key>;
}

impl<T: Clone + Into<Key>> KeyViaInto<T> for KeyProbe<T> {
    fn key(&self, value: &T) -> Option<Key> {
        Some(value.clone().into())
    }
}

#[doc(hidden)]
pub trait KeyFallback<T> {
    fn key(&self, value: &T) -> Option<Key>;
}

impl<T> KeyFallback<T> for &KeyProbe<T> {
    fn key(&self, _: &T) -> Option<Key> {
        None
    }
}

/// The key of the parent of a row of an owned collection, and the position of the row in an
/// ordered list.
pub(crate) struct Parent {
    fk: &'static str,
    key: Key,
    index: Option<(&'static str, i64)>,
}

fn query_error(shape: &ViewShape, sql: &str, source: sqlx::Error) -> Error {
    Error::Query { view: shape.name, path: String::new(), sql: sql.to_string(), source }
}

/// Upsert the row, then make what it owns match it.
pub(crate) fn save_row<'c, B: Backend>(
    conn: &'c mut B::Connection,
    row: RowWrite<B>,
    parent: Option<Parent>,
) -> BoxFuture<'c, Result<(), Error>>
where
    B::Connection: Send,
{
    Box::pin(async move {
        let RowWrite { shape, key, mut columns, mut args, collections, links, variants } = row;
        let key = key.ok_or_else(|| Error::Write {
            view: shape.name,
            message: "it has no key field, so it cannot be saved".to_string(),
        })?;
        let encode = |e: sqlx::error::BoxDynError| Error::Write { view: shape.name, message: e.to_string() };
        if let Some(parent) = parent {
            B::add_key(&mut args, &parent.key).map_err(encode)?;
            columns.push((parent.fk.to_string(), ColumnValue::Bound));
            if let Some((column, index)) = parent.index {
                B::add_key(&mut args, &Key::Int(index)).map_err(encode)?;
                columns.push((column.to_string(), ColumnValue::Bound));
            }
        }
        let sql = statement::upsert(B::DIALECT, shape.table, shape.key_column, &columns);
        B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;

        // The variant tables: the row of the variant, and none in the others
        for (field_index, chosen, variant_row) in variants {
            let FieldKind::Embedded { shape: embedded, .. } = &shape.fields[field_index].kind else { continue };
            let EmbeddedKind::Sum(sum) = &embedded().kind else { continue };
            for variant in sum.variants {
                let VariantData::Table { shape: table } = &variant.data else { continue };
                if variant.name != chosen {
                    delete_tree::<B>(&mut *conn, table(), vec![key.clone()]).await?;
                }
            }
            if let Some(mut variant_row) = variant_row {
                let table = variant_row.shape;
                B::add_key(&mut variant_row.args, &key).map_err(encode)?;
                variant_row.columns.push((table.key_column.to_string(), ColumnValue::Bound));
                variant_row.key = Some(key.clone());
                save_row::<B>(&mut *conn, variant_row, None).await?;
            }
        }

        // Owned collections: delete the elements that are gone, then upsert the others
        for (field_index, rows) in collections {
            let FieldKind::Child(child) = &shape.fields[field_index].kind else { continue };
            let target = (child.shape)();
            let mut keys = Vec::new();
            for row in &rows {
                keys.push(row.key.clone().ok_or_else(|| Error::Write {
                    view: target.name,
                    message: "it has no key field, so its collection cannot be saved".to_string(),
                })?);
            }
            let existing = select_keys::<B>(&mut *conn, target, target.key_column, child.fk, vec![key.clone()]).await?;
            let gone: Vec<Key> = existing.into_iter().filter(|k| !keys.contains(k)).collect();
            delete_tree::<B>(&mut *conn, target, gone).await?;
            for (position, row) in rows.into_iter().enumerate() {
                let index = child.index.map(|column| (column, position as i64));
                save_row::<B>(&mut *conn, row, Some(Parent { fk: child.fk, key: key.clone(), index })).await?;
            }
        }

        // Many-to-many collections: the links of the row
        for (field_index, links) in links {
            let FieldKind::Child(child) = &shape.fields[field_index].kind else { continue };
            let Some(through) = child.through else { continue };
            let sql = statement::delete_by(B::DIALECT, through.table, child.fk, 1);
            let mut delete_args = B::Arguments::default();
            B::add_keys(&mut delete_args, &KeyList::new(vec![key.clone()]).map_err(|_| encode("mixed keys".into()))?)
                .map_err(encode)?;
            B::execute_args(&mut *conn, sql.clone(), delete_args).await.map_err(|e| query_error(shape, &sql, e))?;
            for (position, link) in links.into_iter().enumerate() {
                let RowWrite { key: target, mut columns, mut args, .. } = link;
                let target = target.ok_or_else(|| encode("a linked value has no key".into()))?;
                B::add_key(&mut args, &key).map_err(encode)?;
                columns.push((child.fk.to_string(), ColumnValue::Bound));
                B::add_key(&mut args, &target).map_err(encode)?;
                columns.push((through.target.to_string(), ColumnValue::Bound));
                if let Some(column) = child.index {
                    B::add_key(&mut args, &Key::Int(position as i64)).map_err(encode)?;
                    columns.push((column.to_string(), ColumnValue::Bound));
                }
                let sql = statement::insert(B::DIALECT, through.table, &columns);
                B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
            }
        }
        Ok(())
    })
}

/// The `select` keys of the rows of `shape`'s table whose `column` is one of `keys`.
async fn select_keys<B: Backend>(
    conn: &mut B::Connection,
    shape: &'static ViewShape,
    select: &str,
    column: &str,
    keys: Vec<Key>,
) -> Result<Vec<Key>, Error> {
    let mut found = Vec::new();
    let Ok(keys) = KeyList::new(keys) else { return Ok(found) };
    for keys in keys.chunks(MAX_KEYS) {
        let sql = statement::select_by(B::DIALECT, shape.table, select, column, keys.len());
        let mut args = B::Arguments::default();
        B::add_keys(&mut args, &keys).map_err(|e| Error::Write { view: shape.name, message: e.to_string() })?;
        let rows = B::fetch_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
        for row in &rows {
            let kind = B::key_kind(B::column_type(row, 0)).ok_or_else(|| Error::Write {
                view: shape.name,
                message: format!("the key column `{select}` cannot hold keys"),
            })?;
            if let Some(key) = B::read_key(row, 0, kind).map_err(|e| query_error(shape, &sql, e))? {
                found.push(key);
            }
        }
    }
    Ok(found)
}

/// Delete the rows of `shape` with the keys, and what they own: the rows of their owned
/// collections, their links, and the rows of their variant tables.
pub(crate) fn delete_tree<'c, B: Backend>(
    conn: &'c mut B::Connection,
    shape: &'static ViewShape,
    keys: Vec<Key>,
) -> BoxFuture<'c, Result<u64, Error>>
where
    B::Connection: Send,
{
    Box::pin(async move {
        if keys.is_empty() {
            return Ok(0);
        }
        for field in shape.fields {
            match &field.kind {
                FieldKind::Child(child) if !child.graph => match child.through {
                    Some(through) => {
                        delete_rows::<B>(&mut *conn, shape, through.table, child.fk, &keys).await.map(drop)?
                    }
                    None => {
                        let target = (child.shape)();
                        let owned =
                            select_keys::<B>(&mut *conn, target, target.key_column, child.fk, keys.clone()).await?;
                        delete_tree::<B>(&mut *conn, target, owned).await.map(drop)?;
                    }
                },
                FieldKind::Embedded { shape: embedded, .. } => {
                    if let EmbeddedKind::Sum(sum) = &embedded().kind {
                        for variant in sum.variants {
                            if let VariantData::Table { shape: table } = &variant.data {
                                delete_tree::<B>(&mut *conn, table(), keys.clone()).await.map(drop)?;
                            }
                        }
                    }
                }
                _ => {}
            }
        }
        delete_rows::<B>(&mut *conn, shape, shape.table, shape.key_column, &keys).await
    })
}

async fn delete_rows<B: Backend>(
    conn: &mut B::Connection,
    shape: &'static ViewShape,
    table: &str,
    column: &str,
    keys: &[Key],
) -> Result<u64, Error> {
    let Ok(keys) = KeyList::new(keys.to_vec()) else { return Ok(0) };
    let mut deleted = 0;
    for keys in keys.chunks(MAX_KEYS) {
        let sql = statement::delete_by(B::DIALECT, table, column, keys.len());
        let mut args = B::Arguments::default();
        B::add_keys(&mut args, &keys).map_err(|e| Error::Write { view: shape.name, message: e.to_string() })?;
        deleted += B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
    }
    Ok(deleted)
}
