//! Writing aggregates: [`crate::save`] and [`crate::delete`].
//!
//! The code generated by `#[derive(View)]` turns a value into a [`RowWrite`]: the columns of
//! its row, with the rows of its owned collections, the links of its many-to-many
//! collections and the rows of its variant tables. Saving it upserts the row, then makes
//! each collection, link table and variant table match the value.

use std::marker::PhantomData;

use mabat_core::shape::{EmbeddedKind, EmbeddedShape, FieldKind, VariantData, ViewShape};
use mabat_core::write::{self as statement, ColumnValue};
use sqlx::{Arguments, Encode, Type};

use crate::backend::{Backend, BoxFuture};
use crate::key::{Key, KeyList};
use crate::{Error, ViewDecoder};

/// The most keys of one statement.
pub(crate) const MAX_KEYS: usize = 1000;

/// The row of a value to write, with what it owns. Also a link of a many-to-many
/// collection, whose key is the key of the linked value.
pub struct RowWrite<B: Backend> {
    shape: &'static ViewShape,
    key: Option<Key>,
    /// Whether the database generates the key: a row without one is inserted, and its key read.
    generated: bool,
    columns: Vec<(String, ColumnValue)>,
    args: B::Arguments,
    /// Owned collections: the field and the rows of its elements, in order.
    collections: Vec<(usize, Vec<RowWrite<B>>)>,
    /// Many-to-many collections: the field and its links, in order.
    links: Vec<(usize, Vec<RowWrite<B>>)>,
    /// Enums stored in a table per variant: the field, the variant, and its row.
    variants: Vec<(usize, &'static str, Option<RowWrite<B>>)>,
    /// Insert or update the whole row, or update the columns given only.
    mode: Mode,
    /// The version column and the version of the value, for optimistic locking.
    version: Option<(String, i64)>,
    /// For an update: the keys of the elements of owned collections that are gone.
    removed: Vec<(usize, Vec<Key>)>,
    /// For an update of an element of an ordered list: its position before.
    previous_position: Option<usize>,
    /// References into a graph (`Ref<T>`), resolved to keys when the graph is saved.
    pub(crate) graph_refs: Vec<GraphRef>,
    /// Collections of references into a graph (`Vec<Ref<T>>`): the field and its elements.
    pub(crate) graph_collections: Vec<(usize, Vec<GraphTarget>)>,
}

/// An entity of a graph: the shape of its type and its index in the arena.
#[derive(Debug, Clone, Copy)]
pub(crate) struct GraphTarget {
    pub(crate) shape: fn() -> &'static ViewShape,
    pub(crate) index: usize,
}

impl GraphTarget {
    /// The entity, as the arenas of the graph identify it.
    pub(crate) fn id(&self) -> (usize, usize) {
        (crate::graph::shape_id((self.shape)()), self.index)
    }
}

/// A to-one reference into a graph, written as the key of the entity it points to.
#[derive(Debug, Clone)]
pub(crate) struct GraphRef {
    pub(crate) column: String,
    pub(crate) target: Option<GraphTarget>,
    pub(crate) optional: bool,
}

/// How a row is written.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Mode {
    /// [`crate::save`]: the whole row, inserted or updated.
    Upsert,
    /// [`crate::save_changes`]: the columns that changed, of a row that exists.
    Update,
}

/// What saving a row produced: its new version, and what the rows of its owned collections
/// produced, in order. Generated code writes it back into the value.
#[derive(Debug, Default)]
pub struct Written {
    key: Option<Key>,
    version: Option<i64>,
    collections: Vec<(usize, Vec<Written>)>,
}

impl Written {
    /// The version of the row after saving it, for a view with a version column.
    #[doc(hidden)]
    pub fn version(&self) -> Option<i64> {
        self.version
    }

    /// The key of the row that the database generated, if it was inserted.
    pub(crate) fn key(&self) -> Option<&Key> {
        self.key.as_ref()
    }

    /// The key the database generated for the row, if it was inserted.
    #[doc(hidden)]
    pub fn generated_key(&self) -> Option<i64> {
        match self.key {
            Some(Key::Int(key)) => Some(key),
            _ => None,
        }
    }

    /// What the elements of the collection `field_index` produced, in order.
    #[doc(hidden)]
    pub fn collection(&self, field_index: usize) -> &[Written] {
        self.collections.iter().find(|(i, _)| *i == field_index).map(|(_, w)| w.as_slice()).unwrap_or(&[])
    }
}

impl<B: Backend> RowWrite<B> {
    #[doc(hidden)]
    pub fn new(shape: &'static ViewShape) -> RowWrite<B> {
        RowWrite {
            shape,
            key: None,
            generated: false,
            columns: Vec::new(),
            args: B::Arguments::default(),
            collections: Vec::new(),
            links: Vec::new(),
            variants: Vec::new(),
            mode: Mode::Upsert,
            version: None,
            removed: Vec::new(),
            previous_position: None,
            graph_refs: Vec::new(),
            graph_collections: Vec::new(),
        }
    }

    /// A to-one reference into a graph: `fk` is written as the key of the entity it points to
    /// when the graph is saved.
    #[doc(hidden)]
    pub fn graph_reference<T: crate::View>(&mut self, fk: &str, target: Option<crate::Ref<T>>, optional: bool) {
        let target = target.map(|r| GraphTarget { shape: T::shape, index: r.index() });
        self.graph_refs.push(GraphRef { column: fk.to_string(), target, optional });
    }

    /// A collection of references into a graph: its elements, in order.
    #[doc(hidden)]
    pub fn graph_collection<T: crate::View>(&mut self, field_index: usize, elements: &[crate::Ref<T>]) {
        let elements = elements.iter().map(|r| GraphTarget { shape: T::shape, index: r.index() }).collect();
        self.graph_collections.push((field_index, elements));
    }

    /// Whether the row or a row it owns has references into a graph.
    pub(crate) fn has_graph_refs(&self) -> bool {
        !self.graph_refs.is_empty()
            || !self.graph_collections.is_empty()
            || self.collections.iter().flat_map(|(_, rows)| rows).any(RowWrite::has_graph_refs)
            || self.variants.iter().filter_map(|(_, _, row)| row.as_ref()).any(RowWrite::has_graph_refs)
    }

    /// Write `column` as `key`, or NULL.
    pub(crate) fn bind_key(&mut self, column: String, key: Option<&Key>) -> Result<(), Error> {
        match key {
            Some(key) => {
                B::add_key(&mut self.args, key).map_err(|e| self.error(format!("cannot encode `{column}`: {e}")))?;
                self.columns.push((column, ColumnValue::Bound));
            }
            None => self.null(column),
        }
        Ok(())
    }

    /// The shape of the row's view.
    pub(crate) fn shape(&self) -> &'static ViewShape {
        self.shape
    }

    /// The key of the row, if it has one yet.
    pub(crate) fn row_key(&self) -> Option<&Key> {
        self.key.as_ref()
    }

    /// The rows the row owns: of its owned collections and its variant tables.
    pub(crate) fn owned_rows_mut(&mut self) -> impl Iterator<Item = &mut RowWrite<B>> {
        self.collections
            .iter_mut()
            .flat_map(|(_, rows)| rows.iter_mut())
            .chain(self.variants.iter_mut().filter_map(|(_, _, row)| row.as_mut()))
    }

    /// The database generates the key: a row without one is inserted, and its key read.
    #[doc(hidden)]
    pub fn generated_key(&mut self) {
        self.generated = true;
    }

    /// Write the columns given only, to a row that exists: for [`crate::save_changes`].
    #[doc(hidden)]
    pub fn update(&mut self) {
        self.mode = Mode::Update;
    }

    /// The version column of the row, with the version of the value.
    #[doc(hidden)]
    pub fn version<V: TryInto<i64> + Copy>(&mut self, column: &str, version: V) -> Result<(), Error> {
        let version = version.try_into().map_err(|_| self.error(format!("the version `{column}` is out of range")))?;
        self.version = Some((column.to_string(), version));
        Ok(())
    }

    /// The keys of the elements of an owned collection that are gone, for an update.
    #[doc(hidden)]
    pub fn removed(&mut self, field_index: usize, keys: Vec<Key>) {
        self.removed.push((field_index, keys));
    }

    fn error(&self, message: String) -> Error {
        Error::Write { view: self.shape.name, message }
    }

    /// Bind a value to a column.
    #[doc(hidden)]
    pub fn bind<'t, T>(&mut self, column: String, value: T) -> Result<(), Error>
    where
        T: Encode<'t, B> + Type<B>,
    {
        self.args.add(value).map_err(|e| self.error(format!("cannot encode `{column}`: {e}")))?;
        self.columns.push((column, ColumnValue::Bound));
        Ok(())
    }

    /// Write NULL to a column.
    #[doc(hidden)]
    pub fn null(&mut self, column: String) {
        self.columns.push((column, ColumnValue::Null));
    }

    /// Write a string literal to a column: the tag of an enum.
    #[doc(hidden)]
    pub fn literal(&mut self, column: String, text: &str) {
        self.columns.push((column, ColumnValue::Literal(text.to_string())));
    }

    #[doc(hidden)]
    pub fn set_key(&mut self, key: Option<Key>) {
        self.key = key;
    }

    /// Write the foreign key of a to-one reference: the key of the referenced value, or NULL.
    #[doc(hidden)]
    pub fn reference(&mut self, fk: &str, key: Option<Key>) -> Result<(), Error> {
        match key {
            Some(key) => {
                B::add_key(&mut self.args, &key).map_err(|e| self.error(format!("cannot encode `{fk}`: {e}")))?;
                self.columns.push((fk.to_string(), ColumnValue::Bound));
            }
            None => self.null(fk.to_string()),
        }
        Ok(())
    }

    /// The elements of an owned collection, in order.
    #[doc(hidden)]
    pub fn collection(&mut self, field_index: usize, rows: Vec<RowWrite<B>>) {
        self.collections.push((field_index, rows));
    }

    /// The links of a many-to-many collection, in order.
    #[doc(hidden)]
    pub fn links(&mut self, field_index: usize, links: Vec<RowWrite<B>>) {
        self.links.push((field_index, links));
    }

    /// The variant of an enum stored in a table per variant, with its row if it has data.
    #[doc(hidden)]
    pub fn variant(&mut self, field_index: usize, variant: &'static str, row: Option<RowWrite<B>>) {
        self.variants.push((field_index, variant, row));
    }

    /// Write NULL to the columns of the variants other than `chosen` of an enum stored in
    /// columns under `prefix`, unless the chosen variant writes them too.
    #[doc(hidden)]
    pub fn null_other_variants(&mut self, shape: &'static EmbeddedShape, prefix: &str, chosen: &str) {
        let EmbeddedKind::Sum(sum) = &shape.kind else { return };
        let mut columns = Vec::new();
        for variant in sum.variants.iter().filter(|v| v.name != chosen) {
            if let VariantData::Columns { fields } = &variant.data {
                columns_of(fields, prefix, &mut columns);
            }
        }
        for column in columns {
            if !self.columns.iter().any(|(c, _)| *c == column) {
                self.null(column);
            }
        }
    }
}

/// The columns of fields stored in a row under `prefix`, with those of embedded values.
fn columns_of(fields: &'static [mabat_core::Field], prefix: &str, out: &mut Vec<String>) {
    for field in fields {
        match &field.kind {
            FieldKind::Column { column, .. } => out.push(format!("{prefix}{column}")),
            FieldKind::Embedded { column_prefix, shape } => match &shape().kind {
                EmbeddedKind::Product { fields } => columns_of(fields, &format!("{prefix}{column_prefix}"), out),
                EmbeddedKind::Sum(sum) => {
                    let prefix = format!("{prefix}{column_prefix}");
                    out.push(format!("{prefix}{}", sum.tag_column));
                    for variant in sum.variants {
                        if let VariantData::Columns { fields } = &variant.data {
                            columns_of(fields, &prefix, out);
                        }
                    }
                }
            },
            FieldKind::Child(_) | FieldKind::ToOne { .. } => {}
        }
    }
}

/// Writing a value as an aggregate. Implemented by `#[derive(View)]` for each database
/// whose feature is enabled.
pub trait ViewEncoder<B: Backend>: ViewDecoder<B> {
    /// The key of the value: its key field, `None` if the view has none, or if its key is
    /// generated by the database and it has not been inserted.
    fn key(&self) -> Option<Key>;

    /// Whether the database generates the key of the view: `#[view(generated)]`.
    fn generated_key() -> bool {
        false
    }

    /// Register the views of the entities of a graph that this view's references lead to.
    #[doc(hidden)]
    fn graph_types(types: &mut crate::graph_write::GraphTypes<B>)
    where
        Self: Sized,
    {
        let _ = types;
    }

    /// The row of the value, with what it owns.
    fn write(&self) -> Result<RowWrite<B>, Error>;

    /// The changes from `before` to the value, as rows to update, insert and delete.
    fn write_changes(&self, before: &Self) -> Result<RowWrite<B>, Error>;

    /// Write back what saving produced: the new versions of the value and of the elements
    /// of its owned collections.
    fn written(&mut self, written: &Written) -> Result<(), Error>;
}

/// Writing an embedded value to the row of the value that contains it.
pub trait EmbeddedEncoder<B: Backend>: crate::EmbeddedDecoder<B> {
    /// Write the columns, whose names start with `prefix`. `field_index` is the index of the
    /// view's field that holds the value, for variant tables.
    fn write_embedded(&self, row: &mut RowWrite<B>, prefix: &str, field_index: usize) -> Result<(), Error>;
}

/// The shape of the table of a variant of an enum stored in a table per variant.
#[doc(hidden)]
pub fn variant_table(shape: &'static EmbeddedShape, variant: &str) -> &'static ViewShape {
    let EmbeddedKind::Sum(sum) = &shape.kind else { unreachable!("{} is not an enum", shape.name) };
    match sum.variants.iter().find(|v| v.name == variant).map(|v| &v.data) {
        Some(VariantData::Table { shape }) => shape(),
        _ => unreachable!("{}::{variant} has no table", shape.name),
    }
}

/// The rows of the elements of a collection for [`crate::save_changes`], with the keys of
/// the elements that are gone: elements found in `before` by key are updated with what
/// changed, the others are saved whole. `extra` adds columns to the row of an element: its
/// index in `after` and in `before`.
#[doc(hidden)]
pub fn changes<'a, E, B>(
    after: Vec<&'a E>,
    before: Vec<&'a E>,
    extra: impl Fn(&mut RowWrite<B>, usize, Option<usize>) -> Result<(), Error>,
) -> Result<(Vec<RowWrite<B>>, Vec<Key>), Error>
where
    E: ViewEncoder<B> + 'a,
    B: Backend,
{
    let before_keys = before.iter().map(|element| target_key::<E, B>(element)).collect::<Result<Vec<_>, _>>()?;
    let mut kept = vec![false; before.len()];
    let mut rows = Vec::with_capacity(after.len());
    for (i, element) in after.iter().enumerate() {
        // An element without a key is new: its key is generated when it is inserted
        let key = element.key();
        let found = key.as_ref().and_then(|key| before_keys.iter().position(|k| k == key));
        if key.is_none() && !E::generated_key() {
            target_key::<E, B>(element)?;
        }
        let row = match found {
            Some(j) => {
                kept[j] = true;
                let mut row = element.write_changes(before[j])?;
                row.previous_position = Some(j);
                extra(&mut row, i, Some(j))?;
                row
            }
            None => {
                let mut row = element.write()?;
                extra(&mut row, i, None)?;
                row
            }
        };
        rows.push(row);
    }
    let removed = before_keys.into_iter().zip(kept).filter(|(_, kept)| !kept).map(|(key, _)| key).collect();
    Ok((rows, removed))
}

/// The key of a referenced or linked value, which needs a key field.
#[doc(hidden)]
pub fn target_key<T: ViewEncoder<B>, B: Backend>(value: &T) -> Result<Key, Error> {
    value.key().ok_or_else(|| Error::Write {
        view: T::shape().name,
        message: if T::generated_key() {
            "it has no key yet, so it cannot be referenced in a write: save it first".to_string()
        } else {
            "it has no key field, so it cannot be referenced in a write".to_string()
        },
    })
}

/// Selects how a column of type `T` is written: through `Encode` if `T` implements it,
/// else as an error when it is saved. See [`crate::json::JsonProbe`] for the technique.
#[doc(hidden)]
pub struct WriteProbe<T, B>(PhantomData<fn() -> (T, B)>);

impl<T, B> WriteProbe<T, B> {
    pub const NEW: WriteProbe<T, B> = WriteProbe(PhantomData);
}

#[doc(hidden)]
pub trait WriteViaEncode<T, B: Backend> {
    fn write_column(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> WriteViaEncode<T, B> for WriteProbe<T, B>
where
    T: for<'t> Encode<'t, B> + Type<B>,
{
    fn write_column(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error> {
        row.bind(column, value)
    }
}

#[doc(hidden)]
pub trait WriteFallback<T, B: Backend> {
    fn write_column(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> WriteFallback<T, B> for &WriteProbe<T, B> {
    fn write_column(&self, row: &mut RowWrite<B>, column: String, _: &T) -> Result<(), Error> {
        let ty = std::any::type_name::<T>();
        Err(row.error(format!("`{column}` cannot be written: {ty} does not implement sqlx::Encode")))
    }
}

/// Selects how two values of type `T` are compared for [`crate::save_changes`]: with
/// `PartialEq` if `T` implements it, else they are taken to differ.
#[doc(hidden)]
pub struct ChangeProbe<T>(PhantomData<fn() -> T>);

impl<T> ChangeProbe<T> {
    pub const NEW: ChangeProbe<T> = ChangeProbe(PhantomData);
}

#[doc(hidden)]
pub trait ChangeViaEq<T> {
    fn changed(&self, after: &T, before: &T) -> bool;
}

impl<T: PartialEq> ChangeViaEq<T> for ChangeProbe<T> {
    fn changed(&self, after: &T, before: &T) -> bool {
        after != before
    }
}

#[doc(hidden)]
pub trait ChangeFallback<T> {
    fn changed(&self, after: &T, before: &T) -> bool;
}

impl<T> ChangeFallback<T> for &ChangeProbe<T> {
    fn changed(&self, _: &T, _: &T) -> bool {
        true
    }
}

/// Selects how a `#[view(json)]` column of type `T` is written: as JSON through `Serialize`
/// if `T` implements it, else as an error when it is saved.
#[doc(hidden)]
pub struct JsonWriteProbe<T, B>(PhantomData<fn() -> (T, B)>);

impl<T, B> JsonWriteProbe<T, B> {
    pub const NEW: JsonWriteProbe<T, B> = JsonWriteProbe(PhantomData);
}

#[doc(hidden)]
pub trait JsonWriteViaSerialize<T, B: Backend> {
    fn write_json(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> JsonWriteViaSerialize<T, B> for JsonWriteProbe<T, B>
where
    T: serde::Serialize,
    sqlx::types::Json<serde_json::Value>: for<'t> Encode<'t, B> + Type<B>,
{
    fn write_json(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error> {
        let json = serde_json::to_value(value).map_err(|e| row.error(format!("cannot write `{column}`: {e}")))?;
        // `None` is NULL, not the JSON `null`
        if json.is_null() {
            row.null(column);
            return Ok(());
        }
        row.bind(column, sqlx::types::Json(json))
    }
}

#[doc(hidden)]
pub trait JsonWriteFallback<T, B: Backend> {
    fn write_json(&self, row: &mut RowWrite<B>, column: String, value: &T) -> Result<(), Error>;
}

impl<T, B: Backend> JsonWriteFallback<T, B> for &JsonWriteProbe<T, B> {
    fn write_json(&self, row: &mut RowWrite<B>, column: String, _: &T) -> Result<(), Error> {
        let ty = std::any::type_name::<T>();
        Err(row.error(format!("`{column}` cannot be written: {ty} does not implement serde::Serialize")))
    }
}

/// Selects how the key field of type `T` becomes a [`Key`]: with `Into<Key>` if `T`
/// implements it, else `None`.
#[doc(hidden)]
pub struct KeyProbe<T>(PhantomData<fn() -> T>);

impl<T> KeyProbe<T> {
    pub const NEW: KeyProbe<T> = KeyProbe(PhantomData);
}

#[doc(hidden)]
pub trait KeyViaInto<T> {
    fn key(&self, value: &T) -> Option<Key>;
}

impl<T: Clone + Into<Key>> KeyViaInto<T> for KeyProbe<T> {
    fn key(&self, value: &T) -> Option<Key> {
        Some(value.clone().into())
    }
}

#[doc(hidden)]
pub trait KeyFallback<T> {
    fn key(&self, value: &T) -> Option<Key>;
}

impl<T> KeyFallback<T> for &KeyProbe<T> {
    fn key(&self, _: &T) -> Option<Key> {
        None
    }
}

/// The key of the parent of a row of an owned collection, and the position of the row in an
/// ordered list.
pub(crate) struct Parent {
    fk: &'static str,
    key: Key,
    index: Option<(&'static str, i64)>,
}

fn query_error(shape: &ViewShape, sql: &str, source: sqlx::Error) -> Error {
    Error::Query { view: shape.name, path: String::new(), sql: sql.to_string(), source }
}

/// Write the row, then make what it owns match it: what changed, for an update.
pub(crate) fn save_row<'c, B: Backend>(
    conn: &'c mut B::Connection,
    row: RowWrite<B>,
    parent: Option<Parent>,
) -> BoxFuture<'c, Result<Written, Error>>
where
    B::Connection: Send,
{
    Box::pin(async move {
        let RowWrite {
            shape,
            key,
            generated,
            mut columns,
            mut args,
            collections,
            links,
            variants,
            mode,
            version,
            removed,
            previous_position,
            graph_refs,
            graph_collections,
        } = row;
        // References into a graph are resolved by `save_graph` before a row is written
        debug_assert!(graph_refs.is_empty() && graph_collections.is_empty(), "unresolved graph references");
        let encode = |e: sqlx::error::BoxDynError| Error::Write { view: shape.name, message: e.to_string() };
        let mut written = Written::default();
        // A row whose key the database generates, without one, is new: insert it and read its key
        let inserted = key.is_none() && generated;
        let key = match key {
            Some(key) => key,
            None if generated && mode == Mode::Upsert => {
                if let Some(parent) = &parent {
                    B::add_key(&mut args, &parent.key).map_err(encode)?;
                    columns.push((parent.fk.to_string(), ColumnValue::Bound));
                    if let Some((column, index)) = parent.index {
                        B::add_key(&mut args, &Key::Int(index)).map_err(encode)?;
                        columns.push((column.to_string(), ColumnValue::Bound));
                    }
                }
                if let Some((column, current)) = &version {
                    B::add_key(&mut args, &Key::Int(*current)).map_err(encode)?;
                    columns.push((column.clone(), ColumnValue::Bound));
                    written.version = Some(*current);
                }
                let sql = statement::insert_generated(B::DIALECT, shape.table, shape.key_column, &columns);
                let key = B::insert_generated(&mut *conn, sql.clone(), std::mem::take(&mut args))
                    .await
                    .map_err(|e| query_error(shape, &sql, e))?;
                written.key = Some(key.clone());
                key
            }
            None if generated => {
                return Err(Error::Write {
                    view: shape.name,
                    message: "it has no key yet, so it has no changes to save: save it with `save`, which inserts it \
                              and writes back the key the database generates"
                        .to_string(),
                });
            }
            None => {
                return Err(Error::Write {
                    view: shape.name,
                    message: "it has no key field, so it cannot be saved".to_string(),
                });
            }
        };
        let conflict = || Error::Conflict { view: shape.name, key: format!("{key:?}") };

        match mode {
            _ if inserted => {}
            Mode::Upsert => {
                if let Some(parent) = &parent {
                    B::add_key(&mut args, &parent.key).map_err(encode)?;
                    columns.push((parent.fk.to_string(), ColumnValue::Bound));
                    if let Some((column, index)) = parent.index {
                        B::add_key(&mut args, &Key::Int(index)).map_err(encode)?;
                        columns.push((column.to_string(), ColumnValue::Bound));
                    }
                }
                match &version {
                    // The row is updated, else inserted: by the upsert, which updates a row inserted
                    // meanwhile. A view of some of the columns fails only if the row is new.
                    None => {
                        let mut update_args = B::clone_args(&args);
                        B::add_key(&mut update_args, &key).map_err(encode)?;
                        let sql = statement::update(B::DIALECT, shape.table, shape.key_column, &columns, None);
                        let updated = B::execute_args(&mut *conn, sql.clone(), update_args)
                            .await
                            .map_err(|e| query_error(shape, &sql, e))?;
                        if updated == 0 {
                            let sql = statement::upsert(B::DIALECT, shape.table, shape.key_column, &columns);
                            B::execute_args(&mut *conn, sql.clone(), args)
                                .await
                                .map_err(|e| query_error(shape, &sql, e))?;
                        }
                    }
                    // The row with the version is updated, else a row is inserted unless one has the key
                    Some((column, current)) => {
                        let mut update_args = B::clone_args(&args);
                        B::add_key(&mut update_args, &key).map_err(encode)?;
                        B::add_key(&mut update_args, &Key::Int(*current)).map_err(encode)?;
                        let sql = statement::update(B::DIALECT, shape.table, shape.key_column, &columns, Some(column));
                        let updated = B::execute_args(&mut *conn, sql.clone(), update_args)
                            .await
                            .map_err(|e| query_error(shape, &sql, e))?;
                        if updated > 0 {
                            written.version = Some(current + 1);
                        } else {
                            B::add_key(&mut args, &Key::Int(*current)).map_err(encode)?;
                            columns.push((column.clone(), ColumnValue::Bound));
                            if B::DIALECT == mabat_core::sql::Dialect::MySql {
                                B::add_key(&mut args, &key).map_err(encode)?;
                            }
                            let sql = statement::insert_if_absent(B::DIALECT, shape.table, shape.key_column, &columns);
                            let inserted = B::execute_args(&mut *conn, sql.clone(), args)
                                .await
                                .map_err(|e| query_error(shape, &sql, e))?;
                            if inserted == 0 {
                                return Err(conflict());
                            }
                            written.version = Some(*current);
                        }
                    }
                }
            }
            Mode::Update => {
                // A moved element of an ordered list writes its new position
                if let Some(Parent { index: Some((column, index)), .. }) = &parent
                    && previous_position != Some(*index as usize)
                {
                    B::add_key(&mut args, &Key::Int(*index)).map_err(encode)?;
                    columns.push((column.to_string(), ColumnValue::Bound));
                }
                written.version = version.as_ref().map(|(_, current)| *current);
                // Nothing changed: no statement, and the version stays
                if !columns.is_empty() {
                    B::add_key(&mut args, &key).map_err(encode)?;
                    if let Some((_, current)) = &version {
                        B::add_key(&mut args, &Key::Int(*current)).map_err(encode)?;
                    }
                    let version_column = version.as_ref().map(|(column, _)| column.as_str());
                    let sql = statement::update(B::DIALECT, shape.table, shape.key_column, &columns, version_column);
                    let updated = B::execute_args(&mut *conn, sql.clone(), args)
                        .await
                        .map_err(|e| query_error(shape, &sql, e))?;
                    if updated == 0 {
                        return Err(conflict());
                    }
                    written.version = version.as_ref().map(|(_, current)| current + 1);
                }
            }
        }

        // The variant tables: the row of the variant, and none in the others
        for (field_index, chosen, variant_row) in variants {
            let FieldKind::Embedded { shape: embedded, .. } = &shape.fields[field_index].kind else { continue };
            let EmbeddedKind::Sum(sum) = &embedded().kind else { continue };
            for variant in sum.variants {
                let VariantData::Table { shape: table } = &variant.data else { continue };
                if variant.name != chosen && !inserted {
                    delete_tree::<B>(&mut *conn, table(), vec![key.clone()]).await?;
                }
            }
            if let Some(mut variant_row) = variant_row {
                let table = variant_row.shape;
                B::add_key(&mut variant_row.args, &key).map_err(encode)?;
                variant_row.columns.push((table.key_column.to_string(), ColumnValue::Bound));
                variant_row.key = Some(key.clone());
                variant_row.mode = Mode::Upsert;
                save_row::<B>(&mut *conn, variant_row, None).await?;
            }
        }

        // Owned collections: delete the elements that are gone, then save the others
        for (field_index, rows) in collections {
            let FieldKind::Child(child) = &shape.fields[field_index].kind else { continue };
            let target = (child.shape)();
            let gone = match mode {
                Mode::Update => {
                    removed.iter().find(|(i, _)| *i == field_index).map(|(_, k)| k.clone()).unwrap_or_default()
                }
                // A row just inserted owns nothing yet
                Mode::Upsert if inserted => Vec::new(),
                Mode::Upsert => {
                    let mut keys = Vec::new();
                    for row in &rows {
                        match &row.key {
                            Some(key) => keys.push(key.clone()),
                            // A new element, whose key the database generates
                            None if row.generated => {}
                            None => {
                                return Err(Error::Write {
                                    view: target.name,
                                    message: "it has no key field, so its collection cannot be saved".to_string(),
                                });
                            }
                        }
                    }
                    let existing =
                        select_keys::<B>(&mut *conn, target, target.key_column, child.fk, vec![key.clone()]).await?;
                    existing.into_iter().filter(|k| !keys.contains(k)).collect()
                }
            };
            delete_tree::<B>(&mut *conn, target, gone).await?;
            let mut elements = Vec::with_capacity(rows.len());
            for (position, row) in rows.into_iter().enumerate() {
                let index = child.index.map(|column| (column, position as i64));
                let parent = Parent { fk: child.fk, key: key.clone(), index };
                elements.push(save_row::<B>(&mut *conn, row, Some(parent)).await?);
            }
            written.collections.push((field_index, elements));
        }

        // Many-to-many collections: the links of the row
        for (field_index, links) in links {
            let FieldKind::Child(child) = &shape.fields[field_index].kind else { continue };
            let Some(through) = child.through else { continue };
            if !inserted {
                let sql = statement::delete_by(B::DIALECT, through.table, child.fk, 1);
                let mut delete_args = B::Arguments::default();
                B::add_keys(
                    &mut delete_args,
                    &KeyList::new(vec![key.clone()]).map_err(|_| encode("mixed keys".into()))?,
                )
                .map_err(encode)?;
                B::execute_args(&mut *conn, sql.clone(), delete_args).await.map_err(|e| query_error(shape, &sql, e))?;
            }
            for (position, link) in links.into_iter().enumerate() {
                let RowWrite { key: target, mut columns, mut args, .. } = link;
                let target = target.ok_or_else(|| encode("a linked value has no key".into()))?;
                B::add_key(&mut args, &key).map_err(encode)?;
                columns.push((child.fk.to_string(), ColumnValue::Bound));
                B::add_key(&mut args, &target).map_err(encode)?;
                columns.push((through.target.to_string(), ColumnValue::Bound));
                if let Some(column) = child.index {
                    B::add_key(&mut args, &Key::Int(position as i64)).map_err(encode)?;
                    columns.push((column.to_string(), ColumnValue::Bound));
                }
                let sql = statement::insert(B::DIALECT, through.table, &columns);
                B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
            }
        }
        Ok(written)
    })
}

/// The `select` keys of the rows of `shape`'s table whose `column` is one of `keys`.
pub(crate) async fn select_keys<B: Backend>(
    conn: &mut B::Connection,
    shape: &'static ViewShape,
    select: &str,
    column: &str,
    keys: Vec<Key>,
) -> Result<Vec<Key>, Error> {
    let mut found = Vec::new();
    let Ok(keys) = KeyList::new(keys) else { return Ok(found) };
    for keys in keys.chunks(MAX_KEYS) {
        let sql = statement::select_by(B::DIALECT, shape.table, select, column, keys.len());
        let mut args = B::Arguments::default();
        B::add_keys(&mut args, &keys).map_err(|e| Error::Write { view: shape.name, message: e.to_string() })?;
        let rows = B::fetch_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
        for row in &rows {
            let kind = B::key_kind(B::column_type(row, 0)).ok_or_else(|| Error::Write {
                view: shape.name,
                message: format!("the key column `{select}` cannot hold keys"),
            })?;
            if let Some(key) = B::read_key(row, 0, kind).map_err(|e| query_error(shape, &sql, e))? {
                found.push(key);
            }
        }
    }
    Ok(found)
}

/// Delete the rows of `shape` with the keys, and what they own: the rows of their owned
/// collections, their links, and the rows of their variant tables.
pub(crate) fn delete_tree<'c, B: Backend>(
    conn: &'c mut B::Connection,
    shape: &'static ViewShape,
    keys: Vec<Key>,
) -> BoxFuture<'c, Result<u64, Error>>
where
    B::Connection: Send,
{
    Box::pin(async move {
        if keys.is_empty() {
            return Ok(0);
        }
        for field in shape.fields {
            match &field.kind {
                // Its links, also to entities of a graph; the rows of a collection of references
                // are other entities, which it does not own
                FieldKind::Child(child) if child.through.is_some() || !child.graph => match child.through {
                    Some(through) => {
                        delete_rows::<B>(&mut *conn, shape, through.table, child.fk, &keys).await.map(drop)?
                    }
                    None => {
                        let target = (child.shape)();
                        let owned =
                            select_keys::<B>(&mut *conn, target, target.key_column, child.fk, keys.clone()).await?;
                        delete_tree::<B>(&mut *conn, target, owned).await.map(drop)?;
                    }
                },
                FieldKind::Embedded { shape: embedded, .. } => {
                    if let EmbeddedKind::Sum(sum) = &embedded().kind {
                        for variant in sum.variants {
                            if let VariantData::Table { shape: table } = &variant.data {
                                delete_tree::<B>(&mut *conn, table(), keys.clone()).await.map(drop)?;
                            }
                        }
                    }
                }
                _ => {}
            }
        }
        delete_rows::<B>(&mut *conn, shape, shape.table, shape.key_column, &keys).await
    })
}

async fn delete_rows<B: Backend>(
    conn: &mut B::Connection,
    shape: &'static ViewShape,
    table: &str,
    column: &str,
    keys: &[Key],
) -> Result<u64, Error> {
    let Ok(keys) = KeyList::new(keys.to_vec()) else { return Ok(0) };
    let mut deleted = 0;
    for keys in keys.chunks(MAX_KEYS) {
        let sql = statement::delete_by(B::DIALECT, table, column, keys.len());
        let mut args = B::Arguments::default();
        B::add_keys(&mut args, &keys).map_err(|e| Error::Write { view: shape.name, message: e.to_string() })?;
        deleted += B::execute_args(&mut *conn, sql.clone(), args).await.map_err(|e| query_error(shape, &sql, e))?;
    }
    Ok(deleted)
}
