//! Keys generated by the database, on every database: a new aggregate is saved with no keys,
//! and the keys the database generates for it and for what it owns are written back.

use mabat::{Conn, Error, View};
use sqlx::{AssertSqlSafe, Connection, Executor};

/// The schema, with `{big}` and `{int}` the declarations of generated 64 and 32 bit keys.
const SCHEMA: &str = r#"
CREATE TABLE tag (id BIGINT PRIMARY KEY, name VARCHAR(100) NOT NULL);
CREATE TABLE project (id {big}, name VARCHAR(100) NOT NULL, version INT NOT NULL, visibility VARCHAR(20) NOT NULL);
CREATE TABLE public_project (project_id BIGINT PRIMARY KEY REFERENCES project (id), url VARCHAR(100) NOT NULL);
CREATE TABLE task (
    id {int}, project_id BIGINT NOT NULL REFERENCES project (id), title VARCHAR(100) NOT NULL, position INT NOT NULL
);
CREATE TABLE note (id {big}, task_id INT NOT NULL REFERENCES task (id), body VARCHAR(100) NOT NULL);
CREATE TABLE project_tag (
    project_id BIGINT NOT NULL REFERENCES project (id), tag_id BIGINT NOT NULL REFERENCES tag (id),
    PRIMARY KEY (project_id, tag_id)
);
"#;

#[derive(View, Debug, Clone, PartialEq)]
#[view(table = "project")]
struct Project {
    #[view(generated)]
    id: Option<i64>,
    name: String,
    #[view(version)]
    version: i32,
    #[view(embed)]
    visibility: Visibility,
    #[view(child(fk = "project_id", index = "position"))]
    tasks: Vec<Task>,
    #[view(child(through = "project_tag", fk = "project_id", target = "tag_id", order_by = "id"))]
    tags: Vec<Tag>,
}

/// In a table per variant, keyed by the project's generated key.
#[derive(View, Debug, Clone, PartialEq)]
#[view(tag = "visibility", strategy = "table_per_variant")]
enum Visibility {
    #[view(tag_value = "private")]
    Private,
    #[view(tag_value = "public", table = "public_project", key = "project_id")]
    Public { url: String },
}

#[derive(View, Debug, Clone, PartialEq)]
#[view(table = "task")]
struct Task {
    #[view(generated)]
    id: Option<i32>,
    title: String,
    #[view(child(fk = "task_id", order_by = "id"))]
    notes: Vec<Note>,
}

#[derive(View, Debug, Clone, PartialEq)]
#[view(table = "note")]
struct Note {
    #[view(generated)]
    id: Option<i64>,
    body: String,
}

/// Keys assigned by the application.
#[derive(View, Debug, Clone, PartialEq)]
#[view(table = "tag")]
struct Tag {
    id: i64,
    name: String,
}

fn task(title: &str, notes: &[&str]) -> Task {
    Task {
        id: None,
        title: title.into(),
        notes: notes.iter().map(|body| Note { id: None, body: (*body).into() }).collect(),
    }
}

fn new_project(name: &str) -> Project {
    Project {
        id: None,
        name: name.into(),
        version: 0,
        visibility: Visibility::Public { url: format!("https://example.com/{name}") },
        tasks: vec![task("Design", &["Sketch", "Review"]), task("Build", &[])],
        tags: vec![Tag { id: 1, name: "rust".into() }, Tag { id: 2, name: "sql".into() }],
    }
}

async fn load<C: Conn>(conn: &mut C, id: i64) -> Project
where
    Project: mabat::ViewDecoder<C::Backend>,
{
    mabat::load::<Project>().by_key(id).one(conn).await.unwrap()
}

async fn scenario<C: Conn>(conn: &mut C)
where
    C::Backend: Send,
    <C::Backend as sqlx::Database>::Connection: Send,
    Project: mabat::ViewEncoder<C::Backend>,
    Tag: mabat::ViewEncoder<C::Backend>,
{
    for tag in [Tag { id: 1, name: "rust".into() }, Tag { id: 2, name: "sql".into() }] {
        mabat::save(&mut tag.clone(), conn).await.unwrap();
    }

    // A new aggregate: every key is generated, and written back
    let mut project = new_project("alpha");
    mabat::save(&mut project, conn).await.unwrap();
    let id = project.id.expect("the project's key is written back");
    assert!(project.tasks.iter().all(|t| t.id.is_some()), "{project:?}");
    assert!(project.tasks[0].notes.iter().all(|n| n.id.is_some()), "{project:?}");
    assert_eq!(load(conn, id).await, project);

    // Another one gets other keys
    let mut beta = new_project("beta");
    mabat::save(&mut beta, conn).await.unwrap();
    assert_ne!(beta.id, project.id);
    assert_ne!(beta.tasks[0].id, project.tasks[0].id);

    // Saved again, with its keys: updated in place, with a new version; a new task is inserted
    project.name = "Alpha".into();
    project.tasks.insert(0, task("Plan", &["Scope"]));
    mabat::save(&mut project, conn).await.unwrap();
    assert_eq!((project.id, project.version), (Some(id), 1));
    assert!(project.tasks[0].id.is_some() && project.tasks[0].notes[0].id.is_some());
    assert_eq!(load(conn, id).await, project);

    // Only what changed: a new task and note are inserted, a removed task is deleted
    let before = load(conn, id).await;
    let mut after = before.clone();
    after.tasks.remove(1);
    after.tasks[0].notes.push(Note { id: None, body: "Estimate".into() });
    after.tasks.push(task("Ship", &["Release notes"]));
    after.visibility = Visibility::Private;
    mabat::save_changes(&before, &mut after, conn).await.unwrap();
    assert!(after.tasks.iter().all(|t| t.id.is_some()), "{after:?}");
    assert!(after.tasks.iter().flat_map(|t| &t.notes).all(|n| n.id.is_some()), "{after:?}");
    assert_eq!(load(conn, id).await, after);

    // A value that was never saved has no changes to save
    let unsaved = new_project("gamma");
    let error = mabat::save_changes(&unsaved, &mut unsaved.clone(), conn).await.unwrap_err();
    assert!(matches!(&error, Error::Write { .. }) && error.to_string().contains("has no key yet"), "{error}");

    // Deleted by its generated key, with what it owns
    assert!(mabat::delete::<Project, _>(id, conn).await.unwrap());
    assert!(mabat::load::<Project>().by_key(id).optional(conn).await.unwrap().is_none());
    assert_eq!(load(conn, beta.id.unwrap()).await, beta);
}

#[tokio::test]
async fn sqlite() {
    let mut conn = sqlx::SqliteConnection::connect("sqlite::memory:").await.unwrap();
    let schema = SCHEMA.replace("{big}", "INTEGER PRIMARY KEY").replace("{int}", "INTEGER PRIMARY KEY");
    conn.execute(AssertSqlSafe(schema)).await.unwrap();
    scenario(&mut conn).await;
}

#[tokio::test]
async fn postgres() {
    let Ok(url) = std::env::var("MABAT_TEST_DATABASE_URL") else {
        eprintln!("skipping: MABAT_TEST_DATABASE_URL is not set (see scripts/with-postgres.sh)");
        return;
    };
    let mut conn = sqlx::PgConnection::connect(&url).await.unwrap();
    let schema = format!("mabat_generated_{}", std::process::id());
    let setup = format!(
        "DROP SCHEMA IF EXISTS \"{schema}\" CASCADE; CREATE SCHEMA \"{schema}\"; SET search_path TO \"{schema}\""
    );
    conn.execute(AssertSqlSafe(setup)).await.unwrap();
    let ddl = SCHEMA
        .replace("{big}", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        .replace("{int}", "INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    conn.execute(AssertSqlSafe(ddl)).await.unwrap();
    scenario(&mut conn).await;
    conn.execute(AssertSqlSafe(format!("DROP SCHEMA \"{schema}\" CASCADE"))).await.unwrap();
}

#[tokio::test]
async fn mysql() {
    let Ok(url) = std::env::var("MABAT_TEST_MYSQL_URL") else {
        eprintln!("skipping: MABAT_TEST_MYSQL_URL is not set (see scripts/with-mysql.sh)");
        return;
    };
    let mut conn = sqlx::MySqlConnection::connect(&url).await.unwrap();
    let database = format!("mabat_generated_{}", std::process::id());
    let setup = format!("DROP DATABASE IF EXISTS `{database}`; CREATE DATABASE `{database}`; USE `{database}`");
    conn.execute(AssertSqlSafe(setup)).await.unwrap();
    let ddl =
        SCHEMA.replace("{big}", "BIGINT AUTO_INCREMENT PRIMARY KEY").replace("{int}", "INT AUTO_INCREMENT PRIMARY KEY");
    conn.execute(AssertSqlSafe(ddl)).await.unwrap();
    scenario(&mut conn).await;
    conn.execute(AssertSqlSafe(format!("DROP DATABASE `{database}`"))).await.unwrap();
}
