//! Snapshots of a database's schema on every database: tables and views, column types and
//! nullability, generated keys, primary and foreign keys, and the differences after a change.

use mabat::{Conn, schema};
use sqlx::{AssertSqlSafe, Connection, Executor};

/// The schema, with `{key}` the declaration of a generated 64 bit key.
const SCHEMA: &str = r#"
CREATE TABLE team (id {key}, name VARCHAR(100) NOT NULL, motto TEXT);
CREATE TABLE member (
    id BIGINT NOT NULL, team_id BIGINT NOT NULL, name VARCHAR(50),
    PRIMARY KEY (id, team_id), FOREIGN KEY (team_id) REFERENCES team (id)
);
CREATE VIEW team_name AS SELECT id, name FROM team;
"#;

/// Check the snapshot of the schema, and return it.
async fn check<C: Conn>(conn: &mut C) -> schema::Snapshot {
    let snapshot = schema::snapshot(conn).await.unwrap();
    let names: Vec<&str> = snapshot.tables.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(names, ["member", "team", "team_name"]);

    let team = snapshot.table("team").unwrap();
    let columns: Vec<(&str, bool, bool)> =
        team.columns.iter().map(|c| (c.name.as_str(), c.nullable, c.generated)).collect();
    assert_eq!(columns, [("id", false, true), ("name", false, false), ("motto", true, false)]);
    assert!(team.columns.iter().all(|c| !c.r#type.is_empty() && !c.declared.is_empty()), "{team:?}");
    assert_eq!(team.primary_key, ["id"]);
    assert!(!team.view);

    let member = snapshot.table("member").unwrap();
    assert_eq!(member.primary_key, ["id", "team_id"]);
    assert_eq!(member.foreign_keys.len(), 1, "{member:?}");
    let fk = &member.foreign_keys[0];
    assert_eq!(
        (fk.columns.as_slice(), fk.table.as_str(), fk.references.as_slice()),
        (&["team_id".to_string()][..], "team", &["id".to_string()][..])
    );
    assert!(snapshot.table("team_name").unwrap().view);

    // The same schema, the same file; a change, a difference
    let again = schema::snapshot(conn).await.unwrap();
    assert_eq!(again.to_json(), snapshot.to_json());
    assert!(snapshot.differences(&again).is_empty());
    snapshot
}

/// The schema has a new column since the snapshot.
async fn drift<C: Conn>(conn: &mut C, snapshot: &schema::Snapshot) {
    let changed = schema::snapshot(conn).await.unwrap();
    assert_eq!(snapshot.differences(&changed), ["column `team.founded` is in the database but not in the snapshot"]);
}

const ADD_COLUMN: &str = "ALTER TABLE team ADD COLUMN founded DATE";

#[tokio::test]
async fn sqlite() {
    let mut conn = sqlx::SqliteConnection::connect("sqlite::memory:").await.unwrap();
    conn.execute(AssertSqlSafe(SCHEMA.replace("{key}", "INTEGER PRIMARY KEY"))).await.unwrap();
    let snapshot = check(&mut conn).await;
    conn.execute(ADD_COLUMN).await.unwrap();
    drift(&mut conn, &snapshot).await;
}

#[tokio::test]
async fn postgres() {
    let Ok(url) = std::env::var("MABAT_TEST_DATABASE_URL") else {
        eprintln!("skipping: MABAT_TEST_DATABASE_URL is not set (see scripts/with-postgres.sh)");
        return;
    };
    let mut conn = sqlx::PgConnection::connect(&url).await.unwrap();
    let schema = format!("mabat_schema_{}", std::process::id());
    let setup = format!(
        "DROP SCHEMA IF EXISTS \"{schema}\" CASCADE; CREATE SCHEMA \"{schema}\"; SET search_path TO \"{schema}\""
    );
    conn.execute(AssertSqlSafe(setup)).await.unwrap();
    let ddl = SCHEMA.replace("{key}", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    conn.execute(AssertSqlSafe(ddl)).await.unwrap();
    let snapshot = check(&mut conn).await;
    conn.execute(ADD_COLUMN).await.unwrap();
    drift(&mut conn, &snapshot).await;
    conn.execute(AssertSqlSafe(format!("DROP SCHEMA \"{schema}\" CASCADE"))).await.unwrap();
}

#[tokio::test]
async fn mysql() {
    let Ok(url) = std::env::var("MABAT_TEST_MYSQL_URL") else {
        eprintln!("skipping: MABAT_TEST_MYSQL_URL is not set (see scripts/with-mysql.sh)");
        return;
    };
    let mut conn = sqlx::MySqlConnection::connect(&url).await.unwrap();
    let database = format!("mabat_schema_{}", std::process::id());
    let setup = format!("DROP DATABASE IF EXISTS `{database}`; CREATE DATABASE `{database}`; USE `{database}`");
    conn.execute(AssertSqlSafe(setup)).await.unwrap();
    conn.execute(AssertSqlSafe(SCHEMA.replace("{key}", "BIGINT AUTO_INCREMENT PRIMARY KEY"))).await.unwrap();
    let snapshot = check(&mut conn).await;
    conn.execute(ADD_COLUMN).await.unwrap();
    drift(&mut conn, &snapshot).await;
    conn.execute(AssertSqlSafe(format!("DROP DATABASE `{database}`"))).await.unwrap();
}
