//! Database independent core of Refract.
//!
//! - [`shape`]: the static description of a view, generated by `#[derive(View)]`
//! - [`plan`]: the tree of queries that fills a view
//! - [`sql`]: rendering a query plan as PostgreSQL

pub mod plan;
pub mod shape;
pub mod sql;

pub use plan::{ChildPlan, Link, PlanError, QueryPlan, SelectColumn};
pub use shape::{EmbeddedShape, Field, FieldKind, OrderBy, ViewShape};

/// Alias of the key column of the entity selected by a query.
pub const KEY_ALIAS: &str = "$key";

/// Alias of the foreign key column that links a child row to its parent.
pub const PARENT_ALIAS: &str = "$parent";

/// Name of the root query of a plan, see [`QueryPlan::query_name`].
pub const ROOT_QUERY: &str = "$root";

/// Prefix of the alias of a to-one foreign key column, followed by the field name.
pub const REF_ALIAS_PREFIX: &str = "$ref.";
