//! Static description of views.
//!
//! A shape is generated by `#[derive(View)]` as a `static` and is never modified.
//! Shapes reference each other through function pointers so that views can refer to
//! other views, including themselves.

/// The shape of a view: an entity loaded from one table, with its fields.
#[derive(Debug)]
pub struct ViewShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    /// Table the entity is loaded from.
    pub table: &'static str,
    /// Primary key column, used to attach children and resolve references.
    pub key_column: &'static str,
    pub fields: &'static [Field],
}

/// The shape of a value stored in the row of the enclosing view: a struct whose fields are
/// columns of the view's table, or an enum.
#[derive(Debug)]
pub struct EmbeddedShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    pub kind: EmbeddedKind,
}

#[derive(Debug)]
pub enum EmbeddedKind {
    /// A struct. Only [`FieldKind::Column`] and [`FieldKind::Embedded`] fields.
    Product { fields: &'static [Field] },
    /// An enum.
    Sum(SumShape),
}

/// The shape of an enum: a tag column that names the variant, and the data of each variant.
#[derive(Debug)]
pub struct SumShape {
    /// Column holding the tag value of the variant, selected as text.
    pub tag_column: &'static str,
    pub strategy: SumStrategy,
    /// Ignore non-null columns of other variants than the tag names, instead of failing.
    pub lenient: bool,
    pub variants: &'static [Variant],
}

/// Where the data of the variants of an enum is stored.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SumStrategy {
    /// In columns of the enclosing view's table, next to the tag column.
    Tag,
    /// In a table per variant, whose key is the key of the enclosing view.
    TablePerVariant,
}

#[derive(Debug)]
pub struct Variant {
    /// Name of the Rust variant, which is also its path segment.
    pub name: &'static str,
    /// Value of the tag column for the variant.
    pub tag_value: &'static str,
    pub data: VariantData,
}

#[derive(Debug)]
pub enum VariantData {
    /// No data.
    Unit,
    /// Columns of the enclosing view's table ([`SumStrategy::Tag`]). Tuple fields are named
    /// `0`, `1`, ...
    Columns { fields: &'static [Field] },
    /// A row of the variant's table, keyed by the key of the enclosing view
    /// ([`SumStrategy::TablePerVariant`]).
    Table { shape: fn() -> &'static ViewShape },
}

#[derive(Debug)]
pub struct Field {
    /// Name of the Rust field, which is also its path segment.
    pub name: &'static str,
    pub kind: FieldKind,
}

#[derive(Debug)]
pub enum FieldKind {
    /// A column of the view's table.
    Column { column: &'static str },
    /// A struct or an enum stored in the view's row, optionally with a common column prefix.
    Embedded { column_prefix: &'static str, shape: fn() -> &'static EmbeddedShape },
    /// A to-many collection loaded by a child query: rows of the child table whose `fk`
    /// column references the key of this view, or with [`Child::through`], rows linked to
    /// this view by a link table.
    Child(Child),
    /// A to-one reference: the `fk` column of this view references the key of the target view.
    ToOne { fk: &'static str, optional: bool, shape: fn() -> &'static ViewShape },
}

/// A to-many collection, see [`FieldKind::Child`].
#[derive(Debug)]
pub struct Child {
    /// The column referencing the key of the containing view: of the child table, or of the
    /// link table with `through`.
    pub fk: &'static str,
    pub order_by: &'static [OrderBy],
    pub shape: fn() -> &'static ViewShape,
    /// A many-to-many collection through a link table.
    pub through: Option<Through>,
    /// A column whose integer value places each element in the list, whatever the order of
    /// the rows. Of the link table with `through`.
    pub index: Option<&'static str>,
    /// A column whose value is the key of each element in a map. Of the link table with
    /// `through`.
    pub map_key: Option<&'static str>,
    /// The collection contains the view it is a field of, directly or indirectly.
    pub recursion: Option<Recursion>,
}

impl Child {
    /// A collection whose `fk` column references the key of the containing view.
    pub const fn new(fk: &'static str, shape: fn() -> &'static ViewShape) -> Child {
        Child { fk, order_by: &[], shape, through: None, index: None, map_key: None, recursion: None }
    }
}

/// The link table of a many-to-many collection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Through {
    pub table: &'static str,
    /// The column of the link table referencing the key of the child view.
    pub target: &'static str,
}

/// How a recursive collection is loaded.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Recursion {
    /// One query per level, at most `depth` levels.
    Depth(u32),
    /// One `WITH RECURSIVE` query for all levels, at most `depth` levels if given.
    Cte { depth: Option<u32> },
}

/// A column to order by.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OrderBy {
    pub column: &'static str,
    pub descending: bool,
}

impl OrderBy {
    pub const fn asc(column: &'static str) -> Self {
        OrderBy { column, descending: false }
    }

    pub const fn desc(column: &'static str) -> Self {
        OrderBy { column, descending: true }
    }
}
