//! Static description of views.
//!
//! A shape is generated by `#[derive(View)]` as a `static` and is never modified.
//! Shapes reference each other through function pointers so that views can refer to
//! other views, including themselves.

/// The shape of a view: an entity loaded from one table, with its fields.
#[derive(Debug)]
pub struct ViewShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    /// Table the entity is loaded from.
    pub table: &'static str,
    /// Primary key column, used to attach children and resolve references.
    pub key_column: &'static str,
    pub fields: &'static [Field],
}

/// The shape of a struct whose fields are columns of the enclosing view's table.
#[derive(Debug)]
pub struct EmbeddedShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    /// Only [`FieldKind::Column`] and [`FieldKind::Embedded`] fields.
    pub fields: &'static [Field],
}

#[derive(Debug)]
pub struct Field {
    /// Name of the Rust field, which is also its path segment.
    pub name: &'static str,
    pub kind: FieldKind,
}

#[derive(Debug)]
pub enum FieldKind {
    /// A column of the view's table.
    Column { column: &'static str },
    /// A struct stored in columns of the view's table, optionally with a common column prefix.
    Embedded { column_prefix: &'static str, shape: fn() -> &'static EmbeddedShape },
    /// A to-many collection loaded by a child query: rows of the child table whose `fk`
    /// column references the key of this view.
    Child { fk: &'static str, order_by: &'static [OrderBy], shape: fn() -> &'static ViewShape },
    /// A to-one reference: the `fk` column of this view references the key of the target view.
    ToOne { fk: &'static str, optional: bool, shape: fn() -> &'static ViewShape },
}

/// A column to order by.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OrderBy {
    pub column: &'static str,
    pub descending: bool,
}

impl OrderBy {
    pub const fn asc(column: &'static str) -> Self {
        OrderBy { column, descending: false }
    }

    pub const fn desc(column: &'static str) -> Self {
        OrderBy { column, descending: true }
    }
}
