//! Static description of views.
//!
//! A shape is generated by `#[derive(View)]` as a `static` and is never modified.
//! Shapes reference each other through function pointers so that views can refer to
//! other views, including themselves.

/// The shape of a view: an entity loaded from one table, with its fields.
#[derive(Debug)]
pub struct ViewShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    /// Table the entity is loaded from.
    pub table: &'static str,
    /// Primary key column, used to attach children and resolve references.
    pub key_column: &'static str,
    pub fields: &'static [Field],
}

/// The shape of a value stored in the row of the enclosing view: a struct whose fields are
/// columns of the view's table, or an enum.
#[derive(Debug)]
pub struct EmbeddedShape {
    /// Name of the Rust type, used in error messages.
    pub name: &'static str,
    pub kind: EmbeddedKind,
}

#[derive(Debug)]
pub enum EmbeddedKind {
    /// A struct. Only [`FieldKind::Column`] and [`FieldKind::Embedded`] fields.
    Product { fields: &'static [Field] },
    /// An enum.
    Sum(SumShape),
}

/// The shape of an enum: a tag column that names the variant, and the data of each variant.
#[derive(Debug)]
pub struct SumShape {
    /// Column holding the tag value of the variant, selected as text.
    pub tag_column: &'static str,
    pub strategy: SumStrategy,
    /// Ignore non-null columns of other variants than the tag names, instead of failing.
    pub lenient: bool,
    pub variants: &'static [Variant],
}

/// Where the data of the variants of an enum is stored.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SumStrategy {
    /// In columns of the enclosing view's table, next to the tag column.
    Tag,
    /// In a table per variant, whose key is the key of the enclosing view.
    TablePerVariant,
}

#[derive(Debug)]
pub struct Variant {
    /// Name of the Rust variant, which is also its path segment.
    pub name: &'static str,
    /// Value of the tag column for the variant.
    pub tag_value: &'static str,
    pub data: VariantData,
}

#[derive(Debug)]
pub enum VariantData {
    /// No data.
    Unit,
    /// Columns of the enclosing view's table ([`SumStrategy::Tag`]). Tuple fields are named
    /// `0`, `1`, ...
    Columns { fields: &'static [Field] },
    /// A row of the variant's table, keyed by the key of the enclosing view
    /// ([`SumStrategy::TablePerVariant`]).
    Table { shape: fn() -> &'static ViewShape },
}

#[derive(Debug)]
pub struct Field {
    /// Name of the Rust field, which is also its path segment.
    pub name: &'static str,
    pub kind: FieldKind,
}

#[derive(Debug)]
pub enum FieldKind {
    /// A column of the view's table.
    Column { column: &'static str },
    /// A struct or an enum stored in the view's row, optionally with a common column prefix.
    Embedded { column_prefix: &'static str, shape: fn() -> &'static EmbeddedShape },
    /// A to-many collection loaded by a child query: rows of the child table whose `fk`
    /// column references the key of this view.
    Child { fk: &'static str, order_by: &'static [OrderBy], shape: fn() -> &'static ViewShape },
    /// A to-one reference: the `fk` column of this view references the key of the target view.
    ToOne { fk: &'static str, optional: bool, shape: fn() -> &'static ViewShape },
}

/// A column to order by.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OrderBy {
    pub column: &'static str,
    pub descending: bool,
}

impl OrderBy {
    pub const fn asc(column: &'static str) -> Self {
        OrderBy { column, descending: false }
    }

    pub const fn desc(column: &'static str) -> Self {
        OrderBy { column, descending: true }
    }
}
