[package]
name = "mabat-sqlx"
description = "The executor of Mabat views for PostgreSQL, MySQL and SQLite, built on SQLx"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
homepage.workspace = true
keywords = ["sql", "postgres", "sqlx", "views", "orm"]
categories = ["database", "asynchronous"]
readme = "README.md"

[dependencies]
arc-swap.workspace = true
chrono.workspace = true
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
mabat-core.workspace = true
sqlx.workspace = true
sqlx-postgres = { workspace = true, optional = true }
sqlx-mysql = { workspace = true, optional = true }
sqlx-sqlite = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1", default-features = false, features = ["sync"] }
toml.workspace = true
tracing.workspace = true
uuid.workspace = true

[features]
default = ["postgres"]
postgres = ["sqlx/postgres", "dep:sqlx-postgres"]
mysql = ["sqlx/mysql", "dep:sqlx-mysql"]
sqlite = ["sqlx/sqlite", "dep:sqlx-sqlite"]
