//! The Rust types of the columns of a view, used to check queries against the view.

use sqlx::postgres::PgTypeInfo;
use sqlx::{Postgres, Type, TypeInfo};

use crate::View;

/// The `describe` function of a view.
pub(crate) type DescribeFn = fn(&mut Description);

/// The columns of a view with their Rust types, and the views of its child queries.
///
/// Filled by the `describe` function generated by `#[derive(View)]`.
#[derive(Default)]
pub struct Description {
    pub(crate) columns: Vec<ColumnType>,
    /// Describe functions of the views of child and to-one fields, by field index.
    pub(crate) children: Vec<(usize, DescribeFn)>,
}

/// A column of a view and the Rust type it is decoded as.
pub(crate) struct ColumnType {
    pub(crate) alias: String,
    /// `true` for an `Option` field, which may be left out of an override.
    pub(crate) optional: bool,
    pub(crate) rust_type: &'static str,
    /// The PostgreSQL type the Rust type is usually stored as, for messages.
    pub(crate) sql_type: String,
    compatible: fn(&PgTypeInfo) -> bool,
}

impl ColumnType {
    pub(crate) fn accepts(&self, ty: &PgTypeInfo) -> bool {
        (self.compatible)(ty)
    }
}

fn compatible<T: Type<Postgres>>(ty: &PgTypeInfo) -> bool {
    T::compatible(ty)
}

impl Description {
    /// A column decoded as `T`, with the given alias.
    pub fn column<T: Type<Postgres>>(&mut self, alias: impl Into<String>, optional: bool) {
        self.columns.push(ColumnType {
            alias: alias.into(),
            optional,
            rust_type: std::any::type_name::<T>(),
            sql_type: T::type_info().name().to_string(),
            compatible: compatible::<T>,
        });
    }

    /// A child or to-one field whose values are views of type `C`.
    pub fn view<C: View>(&mut self, field_index: usize) {
        self.children.push((field_index, C::describe));
    }

    pub(crate) fn column_type(&self, alias: &str) -> Option<&ColumnType> {
        self.columns.iter().find(|c| c.alias == alias)
    }

    pub(crate) fn child(&self, field_index: usize) -> Option<DescribeFn> {
        self.children.iter().find(|(i, _)| *i == field_index).map(|(_, describe)| *describe)
    }
}

/// A type name without module paths: `Option<String>` for
/// `core::option::Option<alloc::string::String>`.
pub(crate) fn short_type_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut segment = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' || c == ':' {
            segment.push(c);
        } else {
            out.push_str(segment.rsplit("::").next().unwrap_or(""));
            segment.clear();
            out.push(c);
        }
    }
    out.push_str(segment.rsplit("::").next().unwrap_or(""));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn short_type_names() {
        assert_eq!(short_type_name("core::option::Option<alloc::string::String>"), "Option<String>");
        assert_eq!(short_type_name("i64"), "i64");
        assert_eq!(short_type_name("chrono::DateTime<chrono::offset::utc::Utc>"), "DateTime<Utc>");
    }
}
